### ISSUE TITLE
this.content.scrollToBottom(); stopped working

### ISSUE THREAD

**Issue by nishantpant** [driftyco/ionic#11051]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[X ] **2.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
In my chat application, i had the following code which was working fine till last week. The code simply scrolls the chat content to the bottom. But I don't which npm update caused this, but this code has completely stopped working. All the UI does is flash in place as if it is trying to scroll but does not scroll at all. Interesting thing is it works fine in Chrome browser and scrolls as expected. But not on IOS 10.

**Expected behavior:**
this.content.scrollToBottom() should scroll it to the end of the ion-content.

**Steps to reproduce:**

**Related code:**

Code Snippets from .TS file
  @ViewChild(Content) content: Content;

  ionViewDidEnter() {
      setTimeout(() => {
          this.content.scrollToBottom();
      }, 500);
 }

**Other information:**
I have tried without setTimeOut. Also, tried adding this.content.scrollToBottom(300). But nothing works. I never touched this code, so obviously something else broke it. 

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
Your system information:

 ordova CLI: 6.5.0
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.2.5
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! This has been fixed in 3.0 which was just released a few minutes ago (:

**Comment by nishantpant** [comment]
Thanks would be great. If you could link to docs on how to upgrade to ionic3 that will be great. All i see out there is IONIC 3 beta is out, but I don't want to upgrade to beta on our production software. 

Everywhere on your site, docs and blogs, you still have announcements like 'Announcing IONIC 2.0 final!'

**Comment by manucorporat** [comment]
I didn't notice it was a UIWebView only issue.

I am working in a good fix for UI right now. But in the meantime, what is stoping you to use WKWebView? We have plans to deprecate UI very soon, making WK the default option.

**Comment by nishantpant** [comment]
I upgrade to ionic 3 beta, and the issue still exists.

**Comment by manucorporat** [comment]
@nishantpant could try this nightly release?
 ionic-angular@3.0.0-201704061344

**Comment by wodka** [comment]
I'm having the same issue on ios as well (tried version 2.3 and 3.0), but I'm already using WKWebVies (or at least it claims to be).

<img width="294" alt="screen shot 2017-04-07 at 14 38 00" src="https://cloud.githubusercontent.com/assets/385731/24800366/1b8f96d8-1ba0-11e7-967c-8873d039a74e.png">

scrollToBottom is working fine on android and was also working in 2.2.0

**Comment by nishantpant** [comment]
I just pulled all latest updates to ionic3 and this seems fixed now.

**Comment by HarrisonCroaker** [comment]
Not working on ionic 4 :'(
