### ISSUE TITLE
Touch events not working in Android 4.4.2

### ISSUE THREAD

**Issue by marcsyp** [driftyco/ionic#1729]
It appears that Android 4.4.2 is not playing nicely with touch events.  Using the on-swipe directives in Ionic is extremely unreliable, with swipe events detected only 1 in 10 or 1 in 50 times on a Samsung Galaxy S5 or Nexus 5.  Swipe detection is fine in earlier Android versions.

This appears to be similar if not identical to an issue that is known to be causing problems in other frameworks like JQuery Mobile.  Some reference material:

JQM issue (still open):
https://github.com/jquery/jquery-mobile/issues/5534#issuecomment-47641974

Android shim (workaround):
https://github.com/TNT-RoX/android-swipe-shim

I would also be interested in understanding why the swipes for ion-slide-box are unaffected...

**Comment by devjavedmohd** [comment]
I am also suffer this issue on mobile android (4.4.4) device. if i am debug application in browser scrolling on click is working but if i am tap on mobile it is not working. how can i fix it.

**Comment by marcsyp** [comment]
FYI, this workaround eliminates all scrolling in my Ionic app (Beta13).
Also doesn't help with the tap-hold issue I've been having.  Still in
search of a solution.



On Sun, Nov 30, 2014 at 1:39 PM, JerryBels <notifications@github.com> wrote:

> Had this issue on Android 4.4 on many emulators and a Oneplus with
> Cyanogenmod (based on Android 4.4). Easiest workaround found is to add to
> the JS :
>
> document.ontouchmove = function(event) {
> event.preventDefault();
> };
>
> Not sure about the quality of that workaround... Performance and battery
> consumption speaking.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/driftyco/ionic/issues/1729#issuecomment-65001489>.
>



-- 
Marc Syp, Creative Technologist
San Francisco, CA

WARNING: The information contained in this message is legally
privileged and proprietary information intended only for the use of
the individual or entity named above. If the reader of this message is
not the intended recipient, you are hereby notified that any
dissemination, distribution, or copy of this message is strictly
prohibited. If you have received this message in error, please
immediately delete the original message and notify the sender.
Communication of the information contained in this message to any
unauthorized persons may be a violation of state or federal laws.

**Comment by PureSpider** [comment]
The on-hold directive also does not work reliably for me on android 4.4.4 or 5.0.1.
Sometimes the hold is recognized, sometimes it is not, seemingly random.

**Comment by SashaGeekette** [comment]
Interesting. On my 4.4.4 the on-hold is not working 99% of the time. However, just got a Nexus 9 with 5.0.1 and seems to be working just fine. Until @PureSpider's post, I was thinking that maybe it was something that broke with 4.4.4 and then was fixed with 5. Has anyone tried using Ionic's Crosswalk support and seeing if the newest WebView resolves this? I just haven't had the time yet.

**Comment by PureSpider** [comment]
It works more reliable on 4.4.4 than on 5.0.1 for me, still not very reliable at all on either.

**Comment by rafaellop** [comment]
Regarding touch events, I can recommend this repo: https://github.com/ilmente/mnTouch
Touches on buttons are now hiperquick.

**Comment by DEllingsworth** [comment]
I also was able to get the onHold to work with mnTouch.
Tested on multiple devices/versions including iOS.  

However, we are using the 'hold' with a $ionicPopover. When using mnTOuch on hold events near the top of the screen, the popover will position the topleft corner off the screen.  This does not happen every time, but it does happen frequently enough.   We are still researching the issue.

**Comment by PureSpider** [comment]
Does mnTouch work well with ionic's own touch handling though?

**Comment by rafaellop** [comment]
@DEllingsworth I had the same issue. There's something wrong with the $event in the mnTouch but can be easily overriden by calling the Ionic popover with the window.event. e.g.:

```
  $scope.onHold = function() {
  	$event = window.event;
	$scope.openPopover($event);
  }
```

I'd love to see in Ionic the hiper quick response to touches from mnTouch.

Cheers,
Rafal

**Comment by DEllingsworth** [comment]
Here is a codepen showing the difference between mnTouch and the normal ionic hold.
http://codepen.io/dellingsworth/pen/wBdQzr

**Comment by JerryBels** [comment]
@DEllingsworth I can't see any difference...

**Comment by DEllingsworth** [comment]
I updated the instructions on the codepen.  Do a longpress in the two rows to see the difference. You will see that different elements are returned.

**Comment by rafaellop** [comment]
@DEllingsworth I've written, that the mn has some issues with the $event. Just use the window.event as I shown and it will be ok.

**Comment by DEllingsworth** [comment]
@rafaellop I've added your suggested code to the codepen and it doesn't seem to work. What am i missing?
http://codepen.io/dellingsworth/pen/rawNBq

**Comment by rafaellop** [comment]
@DEllingsworth I'm sorry, but this seems like a stupid mistake from my side. Please ignore.

**Comment by Tomino2112** [comment]
This is also not working for me, I tried to use drag events to replicate very simple version of 9 point mobile lock. Everything works fine on the desktop but on mobile it selects only the first point and does nothing while dragging. There is alert at the drag end that shows the combination you selected, and that fires correctly on the dragend event. So I suppose dragstart and dragend are fine, but drag isn't .

I seen above someone said it woud be good to fix after version1, which is a little surprising, I mean ionic is framework for hybrid apps, I would think that touch events would be among the highest priorities... 

You can clone the repo here: https://github.com/Tomino2112/ionic-mobile-lock I didn't do almost anything with it, so simply add platform (android) and build. 

I have been testing it on Nexus 5, Android 5.0.1

**Comment by SashaGeekette** [comment]
@Tomino2112 You may want to see if using mnTouch for those gestures will fix the issue for now, as it worked with our issue with onhold

**Comment by madgrizzle** [comment]
mn-touch worked as a replacement for on-swipe-left and on-swipe-right for me and my 4.4.4 phone.  Was very easy to implement as a replacement (add mn dependency, add mn-touch to the element and change on-swipe-right and on-swipe-left to swipe-right and swipe-left, respectively).  Vertical scrolling of my overflow-scroll list was unaffected.

**Comment by Tomino2112** [comment]
I don't really see easy way to implement mntouch, it takes care of swiping, but I really need dragging.

**Comment by adamdbradley** [comment]
@rafaellop I'm sorry but I'm not seeing the differences in you codepen examples.

**Comment by adamdbradley** [comment]
Please give the nightly build a test to see if it fixes your issues with this fix: https://github.com/driftyco/ionic/commit/a5881eaeba7d12d016fe3712c77261e75e863cf3

**Comment by Tomino2112** [comment]
I can test it couple of hours

**Comment by Tomino2112** [comment]
Ok, I am happy to tell you that the drag event is being triggered correctly now. BUT there is still problem that is fatal for my app. After a lot of debugging I noticed that the event target doesn't change while dragging. 

This means if I have a div with .class1 and another div with .class2 when I drag over from .class1 to .class2 , the target of the event is still .class1 (drag event is attached to the parent of these two)

What I do in my script is on every drag fire I check "does the e.target=.class2 element?" if yes, do something, if not, ignore. 

This sounds to me like some bug in HammerJS?

By the way I checked the e.gesture.target, same thing

Works fine on desktop.

**Comment by MartinMa** [comment]
:+1: Thanks! @adamdbradley 's patch fixes the *touchcancel issue* for me too! It appeared after I updated a Samsung Galaxy Tab 3 device to Android 4.4.2 (from 4.0 something).

The first *touchmove* event (drag respectively) was fired reliably, but immediately followed by *touchcancel*, which results in a *release* event by the ionic-ified hammer.js implementation.

**Comment by ildarkayumov** [comment]
Hi, i'm using Ionic Version: 1.0.0-rc.0. It's good working on web, but when i run on real device app didn't show swipe animation, but swipe is working. Maybe i didn't understand the swipe animation process on Android and it didn't show that animation on Android.

For example, http://codepen.io/dellingsworth/full/rawNBq/
No swipe/default state - http://joxi.ru/Y2LkY6DhG7nlm6
With swipe animation - http://joxi.ru/J2b3V6XfE0XwA6

You can repeat that using only browser Google Chrome:
1. open http://codepen.io/dellingsworth/full/rawNBq/
2. open development tools - Shift+Ctrl+I
3. click on mobile icon on top left corner - http://joxi.ru/EA46zQbIqoo1mb
4. select any Android device, for example: nexus 5
5. reload page
Then i can't see swipe animation. It didn't repeats with WP or iOs - they are working normal. The same bug on real Android device. Do any have the same problem?

Thank you.

**Comment by abeninski** [comment]
on-release is not working for me guys.
It is fired when moving my finger a little without releasing.

**Comment by MartinMa** [comment]
Hey, I think there was a regression regarding the fix above with this [commit from 19 Mar](https://github.com/driftyco/ionic/commit/e917cae3346ba3e78e5a4126704bdc102e33ae95#commitcomment-10524461).

Maybe @perrygovier can have a look into this? What exactly do you mean by "Prevent gestures from breaking native scrolling"? Is there a use/test case? I could't find a related issue.

@abeninski There is a work around. You have to pass `{prevent_default_directions = ['left', 'right']}` as fourth argument to `$ionicGesture.on`.

P.S I'm going to prepare a codepen to demonstrate the issue.

**Comment by gregor-srdic** [comment]
I have also encountered a problem with "on-hold" not working on galaxy S6 android 5.0.2
In web browser and in emulator android 4.4.2 it works no problem

  `<a class="button" ng-class="..." ng-click="doStuffOnClick()" on-hold="doStuffOnHold()"></a>` doStuffOnHold function is not invoked on the devicewith android 5.0.2

**Comment by MartinMa** [comment]
Please reopen this issue or should a new one be created?

**Comment by perrygovier** [comment]
Please open a new issue, this is different enough from the original issue.

**Comment by manugb** [comment]
On-hold events sometimes is not working, testing with motog android 5.0.1
