### ISSUE TITLE
Collection-Repeat and option/delete buttons

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic#1811]
When using collection repeat and option/delete features, things get pretty funky.

http://codepen.io/mhartington/pen/pnbiy

**Effected Version**: Nightly builds.

**Option Button**: When you swipe on a ion-item to reveal the option buttons, as you scroll down, you will see different items also have their option buttons revealed.

**Delect Button**: If you attempt to delete and item, you will end up deleting two items.

**Comment by danicomas** [comment]
workaround or fix?

**Comment by GNSPS** [comment]
It is already fixed in the nightly! Check out the merge above.

**Comment by danicomas** [comment]
Today? I have added the nightly source in my codepen and doesn't work.

**Comment by GNSPS** [comment]
Strange I used collections and options buttons with a nightly from almost a month ago and everything was fine since November 4. Maybe some bugs resurfaced then...

**Comment by danicomas** [comment]
Other example with nightly build http://plnkr.co/edit/PkSCBIlywziXImgVBAAj?p=preview

http://forum.ionicframework.com/t/collection-repeat-wtih-ion-option-button-in-beta-14/14304

**Comment by danicomas** [comment]
This is not solved, Is it on your roadmap @mhartington? Thnks

**Comment by anwaramoon** [comment]
@mhartington @ajoslin 

This is broken in 1.0.0.rc0 and nightly build. I have updated Mike's codepen with icon fix. Should I raise a new issue or can you reopen this issue?

http://codepen.io/anwaramoon/pen/emLbGO


Thanks

**Comment by danicomas** [comment]
@ajoslin It seems that now is ok!!

One thing. Could you delete all the rows items in the next list? The last item is removed wrong.
http://codepen.io/danicomas/pen/ByWoRP

**Comment by anwaramoon** [comment]
Not really. Try this codepen. http://codepen.io/anwaramoon/pen/emLbGO

**Comment by DrakenZA** [comment]
Not fixed.

**Comment by JWesorick** [comment]
💀

**Comment by tskweres** [comment]
Was this ever fixed?
