### ISSUE TITLE
bug: rc0 Header icons/buttons on left of header bar can't get "activated" class due to swipe to go back change

### ISSUE THREAD

**Issue by djett41** [driftyco/ionic#3348]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When clicking on a button or icon to the left of the screen (x coordinate 45 and under), the activated class never gets added.  

In the activator.js file, there is code that will return if the x coordinate is 45 or under.  (https://github.com/driftyco/ionic/commit/8ebde73d0b8afac1bf1c1787c90a72a28a88bc3a) 

I'm sure theres a reason for this code being added as part of the swipe to go back feature, however this does not give a great UX when clicking buttons/icons on the left side of the screen, especially in the header bar, or in modals

An example of this is in the ionic list demo (http://ionicframework.com/docs/api/directive/ionList/ ).  The delete circle in the header will not get "activated" unless you click outside of the circle to the right.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @djett41!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3348). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3348)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Can you put a codepen together or where you are seeing this?
I wasn't able to replicate this with the nightly builds

**Comment by djett41** [comment]
@mhartington you can replicate it on the ionic codepen /demo for ion-list at http://ionicframework.com/docs/api/directive/ionList/  by clicking on the delete header icon on the left.

**Comment by mhartington** [comment]
should be fixed via 36df508

**Comment by djett41** [comment]
@mhartington @perrygovier Thanks for getting to this quick!  

I'm curious, what would be the side effect of removing the hitX check completely?  While bumping down the check to 30 from 45 looks alot better, any clicks to the left of the icon under 30 still dont get activated of course, which can give off the impression that the click didn't go through.  I have even unconsciously double clicked real fast, thinking that i missed the icon.

Since my app uses nested states, I can't really use the swipe to go back feature anyway unless I change my templates all around which is not on my priority list, so I'm debating forking the repo and removing this code to give users a better experience.  I would just like to understand what else this may break.

**Comment by mhartington** [comment]
@adamdbradley would be able to better understand this.

**Comment by Manduro** [comment]
@adamdbradley Could you please explain the need for this? Still all buttons within 30px of the left side of the screen don't get activated.

**Comment by crazedcoding** [comment]
I am having this exact same issue!!!

showLogOutMenu() never gets called...

  <body ng-app="app" animation="slide-left-right-ios7">
    <ion-side-menus enable-menu-with-back-views="false" data-componentid="side-menu21">
        <ion-side-menu-content>
            <ion-nav-bar class="bar-dark">
                <ion-nav-back-button></ion-nav-back-button>
                <ion-nav-buttons side="left">
                    <button class="button button-icon button-clear ion-navicon" menu-toggle="left"></button>
                </ion-nav-buttons>
            </ion-nav-bar>
            <ion-nav-view></ion-nav-view>
        </ion-side-menu-content>
        <ion-side-menu side="left" id="side-menu21" style="background-color:#000000;">
            <ion-header-bar class="bar-dark">
                <div class="title">Menu</div>
            </ion-header-bar>
            <ion-content padding="false" class="side-menu-left has-header">
                <div data-componentid="html12"></div>
                <h2 id="menu-heading8" style="color:#FFFFFF;font-weight:600;text-align:center;" class=" " data-componentid="heading8">User Name</h2>
                <div data-componentid="image1" style="margin: 0px; line-height: 250px; text-align: center; background-color: rgb(232, 235, 239);">
                    <i class="icon ion-image" style="font-size: 64px; color: rgb(136, 136, 136); vertical-align: middle;"></i>
                </div>
                
                <ion-item id="menu-button26" type="input" class=" button button-balanced  button-block " data-componentid="button26">New Shader</ion-item>
                    <ion-item type="button" ng-click="showLogOutMenu()" class=" button button-positive">Sign Out</ion-item>
  <ion-item class="range range-balanced " id="menu-range1" data-componentid="range1">Resolution
      <input type="range" value="100" min="10" max="100" name="resolution">
          </ion-item>
  <ion-toggle toggle-class="toggle-balanced" id="menu-toggle2" class=" " data-componentid="toggle2">Toggle Sound</ion-toggle>
                <button id="button-view-live" class=" preview-button button button-balanced  button-block ">View Live URL</button>
                <button id="button-dev-link" class=" preview-button button button-balanced  button-block ">Get Developer URL</button>
                <button id="button-live-link" class=" preview-button button button-balanced  button-block ">Get Live URL</button>
            </ion-content>
        </ion-side-menu>
    </ion-side-menus>
  </body>

**Comment by crazedcoding** [comment]
About 36df508: how is decreasing that value supposed to make the side menu any more responsive to my missed inputs (other than putting it to zero / removing it)? I am just getting under the hood of this framework: is there another location in the code that handles inputs for x < 30?

**Comment by dkardanski** [comment]
@mhartington unfortunately, it was not fixed by 36df50863853dcf4faee77cbf40c93c4556c11c1. 
Buttons on the left side of the screen don't get active class added when touched. You have add around 20px left padding for a button for the active class to be added,. However, you need buttons on the left without such puddings e.g. back button.

**Comment by przemekd** [comment]
@mhartington Please reopen this issue, we still has the same exact issue.

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#200
