### ISSUE TITLE
bug: Incorrect content size after keyboard closed

### ISSUE THREAD

**Issue by KillerCodeMonkey** [driftyco/ionic#4193]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>7</span>  <span ionic-webview>webview</span>

<span ionic-description>I have a form with text-, date-inputs and some selectboxes.

1. click in a text input --> keyboard opens
2. click in another "non-keyboard" form-input like a selectbox
3. keyboard is closed but the content is not correct calculated --> there is some free space at the end of the ion-content</span>

<span is-issue-template></span>

**Comment by mhartington** [comment]
Can you put together a codepen for me to test a device?

**Comment by KillerCodeMonkey** [comment]
http://play.ionic.io/m/e17ae4b81904

you can recognize this sometimes on browser (chrome emulation of ios) as well.
click in the input --> select directly the select box choose an option and the black keyboard area is still there. if you click on the body it goes away most of the time, but sometimes it gets stuck.

On mobile device sometimes a little border is never gone on the view.

**Comment by mhartington** [comment]
Not sure what to make of this one. Scrolling/Inputs are a balancing act ATM, maybe @tlancina will know

**Comment by foxgeere** [comment]
We are having a similar issue show up for us on Android today. However for us the space is added in most instances. 

Simple page, with tabs, and a single input box:

![screen shot 2015-09-09 at 08 34 59](https://cloud.githubusercontent.com/assets/10975935/9756512/aaada7c2-56d2-11e5-8e54-45ec9ae1a28a.png)


Tap on the input and the keyboard appears, shows 

![screen shot 2015-09-09 at 08 35 07](https://cloud.githubusercontent.com/assets/10975935/9756513/bae4e75e-56d2-11e5-9fc7-6fb2d2483b58.png)

Close the keyboard and it returns to normal.

The content / scroll height doesn't appear to be getting calculated correctly on open as far as we can see. 

For note, we have android manifest set as adjustPan, app.js has the correct full screen settings and this doesn't happen at all on ios. 

We have no footer and no attach-keyboard in this view. This is a tabbed application.

**Comment by foxgeere** [comment]
Although we are having the issue on 'open' rather than 'close' - it appears the size involved is still the same and perhaps it points to some kind of offset being incorrectly calculated at some stage?

**Comment by mhartington** [comment]
Can you provide a codepen demo @foxgeere

**Comment by tlancina** [comment]
@foxgeere looks like the Android keyboard plugin isn't calculating the height correctly.  What version of Android are you using and on what device?

Also, what is the reported height if you do:

```
window.addEventListener('native.keyboardshow', function(e){
  console.log(e.keyboardHeight);
})
```

Thanks!

**Comment by foxgeere** [comment]
Coming back as 338 (but we are almost sure this is incorrect).

If we remove the ionic keyboard plugin, the gap reduces to only a few pixels. In case that is of use.

We are soon going to try and make a basic app that we can put in the code pen to show the issue... unfortunately it only happens on native device (android) so will take a bit to get that up there

**Comment by foxgeere** [comment]
We also have noticed that ionic keyboard always installs as 1.0.4 but there is a version bump to 1.0.5 but that's not registered on the cordova plugin registry?

**Comment by foxgeere** [comment]
Me again.

So, just threw together a blank tabs app and made the needed setting changes (including android manifest). I've zipped up all the source so you can extract and run (no idea how to get this into a code pen with the applicable android manifest.xml settings etc) 

The issue still happens but the spacing is now different:

![screen shot 2015-09-09 at 16 00 40](https://cloud.githubusercontent.com/assets/10975935/9765439/23e15ab0-570c-11e5-97ef-46aa922aff58.png)


![screen shot 2015-09-09 at 16 00 43](https://cloud.githubusercontent.com/assets/10975935/9765445/2869f4ac-570c-11e5-83f1-8b1a3edfa742.png)


You can see the white space that suddenly appears above the keyboard there.

Let me know if there is anything else I can do to help. 

You can download source in zip here: http://we.tl/B2MMBxOKAK

Ionic info etc is:

Cordova CLI: 5.2.0
Ionic Version: 1.1.0
Ionic CLI Version: 1.6.4
Ionic App Lib Version: 0.3.8
ios-deploy version: 1.5.0
ios-sim version: 3.1.1
OS: Mac OS X Yosemite
Node Version: v0.12.6
Xcode version: Xcode 6.4 Build version 6E35b


com.ionic.keyboard 1.0.4 "Keyboard"
cordova-plugin-console 1.0.1 "Console"
cordova-plugin-device 1.0.1 "Device"
cordova-plugin-splashscreen 2.1.0 "Splashscreen"
cordova-plugin-whitelist 1.0.0 "Whitelist"

**Comment by foxgeere** [comment]
Ultimately all we are trying to achieve is having 'tabs' at the bottom on android without them going above the keyboard when it is opened. It seems this is incredibly tough to achieve. :)

**Comment by jeremy-nicholls** [comment]
I managed to fix the issue reported by KillerCodeMonkey.
Have a look at pull request #4365

**Comment by dozed** [comment]
@jeremy-nicholls and all

This require more fixing, see (*).

It is an issue with Chrome and shifting the container up, getBoundingClientRect().top and the y-translate of the CSS transform differ.

Reproduce: http://output.jsbin.com/fuzomi/#/tab/items
  - Scroll until an input which is off the inital screen
  - Focus it
  - Scroll back to top
  - Type -> Chrome shifts the div up
  - Click on a non-input area to unfocus -> still shifted  (*)
  - Click on an input -> scroll is fixed

A related issue is https://github.com/cubiq/iscroll/issues/964

**Comment by ajeesh13** [comment]
Hi 
I have made a small modification in the ionic bundle.js and it seemed like the problem was fixed.

In the

#### function keyboardFocusIn(e) ,
before the following line

#### keyboardActiveElement = null;
I added the following codes

#### if (keyboardActiveElement) {
#### ionic.trigger('resetScrollView', {
#### target: keyboardActiveElement
#### }, true);
#### }

**Comment by tlancina** [comment]
So I believe that there are really 3 separate issues here: 

1) The scroll content not resizing on iOS 7, which I'm unable to reproduce on iOS 8 and iOS 9.

2) The keyboard plugin reporting incorrect values on Android, causing the scroll content to resize incorrectly.  

3) Chrome automatically dragging focused translated elements into view when they are scrolled offscreen, messing up the scroll content.  We're going to be moving to native scrolling as the default in 1.2, which should get rid of this.

As this issue has gotten slightly convoluted and I'm unable to reproduce the original issue I'm going to close this.  If you are still having problems, please open a new issue with a test case reproducing the specific issue at hand (you can always link back here for reference).  Thanks!

**Comment by hrpatidar** [comment]
Hi All,

Still I facing the above issue. See the steps:

1. Tap on input field --> keyboard opens
2. Tap on app back button from top nav bar --> keyboard closed and back to list screen.
3. But on list screen keyboard is closed but the content is not having correct scroll --> there is some free space at the end of the ion-content. the free space is similar to keyboard height.

Please help me out. I have updated the IONIC version as well with 1.2.4. But still facing. 

Thanks,
Harish

**Comment by alphapilgrim** [comment]
@tlancina, still having this issue. Any fix for this yet, or suggested approach?

**Comment by djx18** [comment]
@hrpatidar I have the same exact issue as you. Ionic thinks the keyboard is open but it's actually closed and the height of the ion content is not correct. 

Even when the keyboard is open the height of the ion content gets confused and doesn't know what the height should be. So I sometimes have a white gap above the keyboard until the start of the ion content.

**Comment by tlancina** [comment]
Hey there, sorry to hear you're having issues.  Are you guys using the Keyboard plugin?

**Comment by djx18** [comment]
I am not using the keyboard plug in  since I am running crosswalk. I'm not using Cordova with crosswalk but just plain old crosswalk.

**Comment by alphapilgrim** [comment]
I am using the keyboard plugin, and have read through other threads alike
with same configuration with no success.

**Comment by emreiser** [comment]
I’m having what appears to be a related issue with Ionic 1.3.1 on Android 5.1 and 6.0.
After the keyboard is opened and closed on a text input, view content is incorrectly sized and the footer bar is pushed off the screen. I am unable to scroll or view the footer bar unless the app is backgrounded and foregrounded again.

Proper content display:
![screenshot_2016-06-28-18-08-12](https://cloud.githubusercontent.com/assets/3493841/16434102/b16a6c2e-3d5b-11e6-8700-62b86c8a8629.png)

With keyboard open:
![screenshot_2016-06-28-18-08-16](https://cloud.githubusercontent.com/assets/3493841/16434122/cab0c732-3d5b-11e6-831e-a8d669fe7a9a.png)

Clipped footer content once keyboard is closed:
![screenshot_2016-06-28-18-08-36](https://cloud.githubusercontent.com/assets/3493841/16434130/d5c7c940-3d5b-11e6-8e16-5201f531c51a.png)

I have the Keyboard plugin installed and have tried to reload the state on keyboard close to no avail. 

In the interim, is there any way to trigger the function called when the app is foregrounded as a temporary fix?

**Comment by adamfellon** [comment]
I ran into a similar issue on Android.  We have a search form at the top of the app that drops down a list of anchor boxes.  When a user selects a search results and is routed from that click the screen size is not calculated correctly.

When I inspect the window I can see the ion-tabs anchors underneath the bottom of the screen and can't scroll down to see them.

Is there an event that I could trigger on click of a search result as a band-aid to get the screen to resize?

Anecdotally, if I cause an alert to happen in the app after my bottom ion-tabs are hidden then the screen resizes itself correctly.  I couldn't find the event that this is firing to be able to just call it on click of the search result or I would have.

**Comment by kunalkaskar** [comment]
I have two tab like screens in one ion-content tag which I show-hide on click. Each tab has one input. When I tap on input keyboard opens and while Keyboard is open if I tap on another tab, ion-content remains in same height as it was when keyboard was open and my view is cut.
