### ISSUE TITLE
bug: bug: Radio buttons have broken logical and visual state on iOS9 device

### ISSUE THREAD

**Issue by zarko-tg** [driftyco/ionic#4347]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>Unpredictable / wrong behaviour of radio buttons / groups on iOS 9.
Build and run Ionic's own http://codepen.io/ionic/pen/saoBG on an iOS 9 device (iPhone). Note that it can only be reproduced on an actual device (and simulator probably).

![img_0009](https://cloud.githubusercontent.com/assets/6142411/9790907/dd10a618-57d8-11e5-88ca-66a93cba7c8a.PNG)

Your system information:

Cordova CLI: 5.3.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.0.1
Ionic CLI Version: 1.6.4
Ionic App Lib Version: 0.3.8
ios-deploy version: 1.7.0 
ios-sim version: 4.1.1 
OS: Mac OS X Yosemite
Node Version: v0.12.7
Xcode version: Xcode 6.4 Build version 6E35b </span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @zarko-tg!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4347). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4347)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
![](http://i.imgur.com/X8NkSX5.jpg)

Confirmed, thanks!

**Comment by mahnuh** [comment]
Any progress with that issue? It makes nearly all my apps unusable :-(

**Comment by mhartington** [comment]
Working on it now

**Comment by Fpds** [comment]
Seems to be a problem with tilde combinator (~). Using plus (+) fixed the problem.

**Comment by mhartington** [comment]
@zarko-tg could you pull down the nightly builds and give it a test please?

**Comment by zarko-tg** [comment]
I would but it's weekend here already and I don't have a Mac at home (yet).
Let's see if someone else from the affected can step in in meantime.

**Comment by pbudner** [comment]
I experienced the same issue, seems to be fixed in the nightly builds.

**Comment by mahnuh** [comment]
Checkboxes do work again, great! But there is still one thing wrong. Custom icons are not working. I am using icon="ion-ios-checkmark-outline", but it displays ion-checkmark.

**Comment by mhartington** [comment]
@mahnuh alright, I know what that is. Give me a sec

**Comment by mhartington** [comment]
@mahnuh do you mind pulling down the nightly builds again and trying that? Should be good now.

**Comment by mahnuh** [comment]
Works like charm! Thanks @mhartington, you are awesome!

**Comment by gabrielmaldi** [comment]
I just tried to reproduce this on the iOS Simulator (`iOS 9.0 (13A340)` with `Xcode 7 GM seed`) and wasn't able to do so. I tried both on Safari and inside a UIWebView.

I forked the original pen and changed Ionic nightly to 1.1.0 (which still uses `~` for radio buttons): http://codepen.io/gabrielmaldi/pen/ojxveB

<img width="283" alt="screen shot 2015-09-16 at 11 22 51 am" src="https://cloud.githubusercontent.com/assets/3728897/9907387/4c823ad0-5c65-11e5-9c75-4fabbab97397.png">

I know that you guys already changed `~` to `+`, but I wanted to know if there would be a problem with my own `~` selectors. Since I couldn't reproduce the issue, I'm assuming that Apple fixed it in some iOS 9 beta release and that now it's safe to use `~`? Or maybe it just reproduces on a device and not the simulator (would be really weird)? It would be really helpful if someone could confirm that there is no longer an issue with `~` on the current release of iOS 9 by trying to reproduce the original problem.

Thanks!

**Comment by mhartington** [comment]
@gabrielmaldi I was still able to break it in ios9 GM as well as ios 9.1 beta 1, so I think it's safe to say it is still broken.

**Comment by gabrielmaldi** [comment]
@mhartington I'll take a deeper look into it then, thanks!

**Comment by seanhelvey** [comment]
This issue was closed, but is there a fix? Stuck trying to get this working in an app right now.

**Comment by skotturi** [comment]
Just discovered this in my Ionic app as well. Any updates? Tmp workarounds?

**Comment by mhartington** [comment]
Yes, this has been fixed in the nighty builds. You read more here. http://blog.ionic.io/preparing-for-ios-9/

**Comment by skotturi** [comment]
Awesome, thanks @mhartington, you guys rock!

**Comment by gebidesign** [comment]
As a quick fix, the following code did the job for me.
Thanks for a suggestion @Fpds 

```scss
/**
 * There is a problem with radio buttons on iOS9
 * where Ionic's '~' combinator for radio button styles
 * doesn't work. Changing it into a '+' combinator fixes it.
 * n.b. might be fixed in later builds
 */
.item-radio input {

  &:checked + .item-content {
    background: #f7f7f7;
  }

  &:checked + .radio-icon {
    visibility: visible;
  }
}
```

**Comment by jonalling** [comment]
@mhartington I am still having issues with radio buttons in iOS 9.1.  I updated to the latest Ionic master, and there was no improvement. A touch on an un-active radio doesn't select it, but a touch on an active radio selects the other un-active radio.  ng-model seems to register correctly though, so it's just the styling.

**Comment by TomDoesRUG** [comment]
I'm experiencing the same issue as @jonalling

**Comment by jonalling** [comment]
@TomDoesRUG I was able to use the <ion-radio-fix> to make it work for now if you need a solution.

http://blog.ionic.io/preparing-for-ios-9/

**Comment by noldotar** [comment]
Same issue here, using directive…
```html
<ion-radio class="no-border bg-white" ng-model="$parent.model" ng-value="null" icon="icon-check-circle positive">{{ t.everything }}</ion-radio>
<ion-radio class="bg-white" ng-repeat="option in options | orderBy: 'label'" ng-model="$parent.$parent.model" ng-value="option.value" icon="icon-check-circle positive">{{ option.label }}</ion-radio>
```
… as with the html directly
```html
<label class="item item-radio no-border">
	<input type="radio" ng-model="$parent.model" ng-value="null">
	<div class="item-content">{{ t.everything }}</div>
	<i class="radio-icon icon-check-circle positive"></i>
</label>
<label ng-repeat="option in options track by option.value | orderBy: 'label'" class="item item-radio">
	<input type="radio" ng-model="$parent.$parent.model" ng-value="option.value">
	<div class="item-content">{{ option.label }}</div>
	<i class="radio-icon icon-check-circle positive"></i>
</label>
```
I'm running it inside the modal, works correctly with every plaftorm but fails in iOS 9.1:
when I'm tapping on a item-radio the things remains the same on the view, but if I'm scrolling the new tapped item displays that it's checked… but the old one remains checked as well; if i'm confirming the modal, data is served correctly.

Any help?

**Comment by mhartington** [comment]
@noldotar so this is fixed in the nightly builds, but you can use a external fix until we cut a new release (hoping to do that soon)


https://gist.github.com/mlynch/064d27912b511a63caa3


The main issue here is iOS9's support of the `~` selector, which is used in the radio css. But in the nightly builds/gist, we've changed the markup and css a bit to fix this.

So if you use the nightly builds or apply the gist, you can use 

```
<ion-radio-fix></ion-radio-fix>
```
As your markup. To make sure it has been applied correctly, you can inspect the element and you should see a `radio-content` div next to the input.

```
      '<label class="item item-radio">' +
        '<input type="radio" name="radio-group">' +
        '<div class="radio-content">' +
          '<div class="item-content disable-pointer-events" ng-transclude></div>' +
          '<i class="radio-icon disable-pointer-events icon ion-checkmark"></i>' +
        '</div>' +
      '</label>'
```

Also, make sure you are including the directive as a dependency. Please let me know if after review this, you still have issues.

**Comment by noldotar** [comment]
Ok, adding the fixes it works in iOS as well. Thanks a lot! Awesome customer care!!!
