### ISSUE TITLE
bug: Native scroll memory leak

### ISSUE THREAD

**Issue by AAJohnJohnson** [driftyco/ionic#4746]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Start with Tabs sample.
Add overflow-scroll="true" to an ion-content directive.
Use Chrome Developer Tools / Record Heap Allocations, then
switch back and forth between page with native scroll and observe memory is leaked.
v1.1.1 

Possible fix:
ionic-bundle.js#7322 (in __cleanup function)
delete:
  container.removeEventListener('resetScrollView', self.resetScrollView);
  (which appears to be a cut & paste of #7318 ???)
add: 
  document.removeEventListener('resetScrollView', self.resetScrollView);</span>

<span is-issue-template></span>

**Comment by mlynch** [comment]
Hey, thanks for the issue. This was _just_ fixed a day or so ago, will be in 1.2!

**Comment by AAJohnJohnson** [comment]
It looks like the above fix is NOT included in 1.2, and testing with V1.2 shows that the native scroll still leaks memory.
Can you please let us know when this fix will be included?

**Comment by lorenzodallavecchia** [comment]
I'm not seeing the fix either. In _js/views/scrollViewNative.js_ a listener is being added on `document` for `resetScrollView`, but there is no corresponding `removeEventListener` call in the `__ckeanup` function.

On the other hand, _js/views/scrollView.js_ has been fixed correctly.

**Comment by rkistner** [comment]
I'm also still getting this issue in 1.2, and it's a *big* memory leak. Since the scrollView is never released, everything inside (DOM elements as well as their scopes) is kept in memory, so the memory increases with every view navigation.

#4807 seems to fix the issue for me.

**Comment by Frozenball** [comment]
I can confirm:
![screen shot 2016-07-14 at 14 19 20](https://cloud.githubusercontent.com/assets/53298/16837775/fefb0588-49cd-11e6-9d8c-c47c986c67e2.png)
