### ISSUE TITLE
bug: Ionic native scroll flickering 1.2.1 (Amsterdam)

### ISSUE THREAD

**Issue by kabus202** [driftyco/ionic#4869]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi,

I want to report a issue with 1.2.1 (amsterdam release). 

It's flickering when menu(sidebar) button is pressed. 

To reproduce: 

1. start a new project sidemenu
2. replace $scope.playlists with this code below 
3. run on device and press menu button (add class item-dark to make it visible).

$scope.playlist = [
  {
    "name": "Tiger Nixon",
    "position": "System Architect",
    "salary": "$320,800",
    "start_date": "2011/04/25",
    "office": "Edinburgh",
    "extn": "5421"
  },
  {
    "name": "Garrett Winters",
    "position": "Accountant",
    "salary": "$170,750",
    "start_date": "2011/07/25",
    "office": "Tokyo",
    "extn": "8422"
  },
  {
    "name": "Ashton Cox",
    "position": "Junior Technical Author",
    "salary": "$86,000",
    "start_date": "2009/01/12",
    "office": "San Francisco",
    "extn": "1562"
  },
  {
    "name": "Cedric Kelly",
    "position": "Senior Javascript Developer",
    "salary": "$433,060",
    "start_date": "2012/03/29",
    "office": "Edinburgh",
    "extn": "6224"
  },
  {
    "name": "Airi Satou",
    "position": "Accountant",
    "salary": "$162,700",
    "start_date": "2008/11/28",
    "office": "Tokyo",
    "extn": "5407"
  },
  {
    "name": "Brielle Williamson",
    "position": "Integration Specialist",
    "salary": "$372,000",
    "start_date": "2012/12/02",
    "office": "New York",
    "extn": "4804"
  },
  {
    "name": "Herrod Chandler",
    "position": "Sales Assistant",
    "salary": "$137,500",
    "start_date": "2012/08/06",
    "office": "San Francisco",
    "extn": "9608"
  },
  {
    "name": "Rhona Davidson",
    "position": "Integration Specialist",
    "salary": "$327,900",
    "start_date": "2010/10/14",
    "office": "Tokyo",
    "extn": "6200"
  },
  {
    "name": "Colleen Hurst",
    "position": "Javascript Developer",
    "salary": "$205,500",
    "start_date": "2009/09/15",
    "office": "San Francisco",
    "extn": "2360"
  },
  {
    "name": "Sonya Frost",
    "position": "Software Engineer",
    "salary": "$103,600",
    "start_date": "2008/12/13",
    "office": "Edinburgh",
    "extn": "1667"
  },
  {
    "name": "Jena Gaines",
    "position": "Office Manager",
    "salary": "$90,560",
    "start_date": "2008/12/19",
    "office": "London",
    "extn": "3814"
  },
  {
    "name": "Quinn Flynn",
    "position": "Support Lead",
    "salary": "$342,000",
    "start_date": "2013/03/03",
    "office": "Edinburgh",
    "extn": "9497"
  },
  {
    "name": "Charde Marshall",
    "position": "Regional Director",
    "salary": "$470,600",
    "start_date": "2008/10/16",
    "office": "San Francisco",
    "extn": "6741"
  },
  {
    "name": "Haley Kennedy",
    "position": "Senior Marketing Designer",
    "salary": "$313,500",
    "start_date": "2012/12/18",
    "office": "London",
    "extn": "3597"
  },
  {
    "name": "Tatyana Fitzpatrick",
    "position": "Regional Director",
    "salary": "$385,750",
    "start_date": "2010/03/17",
    "office": "London",
    "extn": "1965"
  },
  {
    "name": "Michael Silva",
    "position": "Marketing Designer",
    "salary": "$198,500",
    "start_date": "2012/11/27",
    "office": "London",
    "extn": "1581"
  },
  {
    "name": "Paul Byrd",
    "position": "Chief Financial Officer (CFO)",
    "salary": "$725,000",
    "start_date": "2010/06/09",
    "office": "New York",
    "extn": "3059"
  },
  {
    "name": "Gloria Little",
    "position": "Systems Administrator",
    "salary": "$237,500",
    "start_date": "2009/04/10",
    "office": "New York",
    "extn": "1721"
  },
  {
    "name": "Bradley Greer",
    "position": "Software Engineer",
    "salary": "$132,000",
    "start_date": "2012/10/13",
    "office": "London",
    "extn": "2558"
  },
  {
    "name": "Dai Rios",
    "position": "Personnel Lead",
    "salary": "$217,500",
    "start_date": "2012/09/26",
    "office": "Edinburgh",
    "extn": "2290"
  },
  {
    "name": "Jenette Caldwell",
    "position": "Development Lead",
    "salary": "$345,000",
    "start_date": "2011/09/03",
    "office": "New York",
    "extn": "1937"
  },
  {
    "name": "Yuri Berry",
    "position": "Chief Marketing Officer (CMO)",
    "salary": "$675,000",
    "start_date": "2009/06/25",
    "office": "New York",
    "extn": "6154"
  },
  {
    "name": "Caesar Vance",
    "position": "Pre-Sales Support",
    "salary": "$106,450",
    "start_date": "2011/12/12",
    "office": "New York",
    "extn": "8330"
  },
  {
    "name": "Doris Wilder",
    "position": "Sales Assistant",
    "salary": "$85,600",
    "start_date": "2010/09/20",
    "office": "Sidney",
    "extn": "3023"
  },
  {
    "name": "Angelica Ramos",
    "position": "Chief Executive Officer (CEO)",
    "salary": "$1,200,000",
    "start_date": "2009/10/09",
    "office": "London",
    "extn": "5797"
  },
  {
    "name": "Gavin Joyce",
    "position": "Developer",
    "salary": "$92,575",
    "start_date": "2010/12/22",
    "office": "Edinburgh",
    "extn": "8822"
  },
  {
    "name": "Jennifer Chang",
    "position": "Regional Director",
    "salary": "$357,650",
    "start_date": "2010/11/14",
    "office": "Singapore",
    "extn": "9239"
  },
  {
    "name": "Brenden Wagner",
    "position": "Software Engineer",
    "salary": "$206,850",
    "start_date": "2011/06/07",
    "office": "San Francisco",
    "extn": "1314"
  },
  {
    "name": "Fiona Green",
    "position": "Chief Operating Officer (COO)",
    "salary": "$850,000",
    "start_date": "2010/03/11",
    "office": "San Francisco",
    "extn": "2947"
  },
  {
    "name": "Shou Itou",
    "position": "Regional Marketing",
    "salary": "$163,000",
    "start_date": "2011/08/14",
    "office": "Tokyo",
    "extn": "8899"
  },
  {
    "name": "Michelle House",
    "position": "Integration Specialist",
    "salary": "$95,400",
    "start_date": "2011/06/02",
    "office": "Sidney",
    "extn": "2769"
  },
  {
    "name": "Suki Burks",
    "position": "Developer",
    "salary": "$114,500",
    "start_date": "2009/10/22",
    "office": "London",
    "extn": "6832"
  },
  {
    "name": "Prescott Bartlett",
    "position": "Technical Author",
    "salary": "$145,000",
    "start_date": "2011/05/07",
    "office": "London",
    "extn": "3606"
  },
  {
    "name": "Gavin Cortez",
    "position": "Team Leader",
    "salary": "$235,500",
    "start_date": "2008/10/26",
    "office": "San Francisco",
    "extn": "2860"
  },
  {
    "name": "Martena Mccray",
    "position": "Post-Sales support",
    "salary": "$324,050",
    "start_date": "2011/03/09",
    "office": "Edinburgh",
    "extn": "8240"
  },
  {
    "name": "Unity Butler",
    "position": "Marketing Designer",
    "salary": "$85,675",
    "start_date": "2009/12/09",
    "office": "San Francisco",
    "extn": "5384"
  },
  {
    "name": "Howard Hatfield",
    "position": "Office Manager",
    "salary": "$164,500",
    "start_date": "2008/12/16",
    "office": "San Francisco",
    "extn": "7031"
  },
  {
    "name": "Hope Fuentes",
    "position": "Secretary",
    "salary": "$109,850",
    "start_date": "2010/02/12",
    "office": "San Francisco",
    "extn": "6318"
  },
  {
    "name": "Vivian Harrell",
    "position": "Financial Controller",
    "salary": "$452,500",
    "start_date": "2009/02/14",
    "office": "San Francisco",
    "extn": "9422"
  },
  {
    "name": "Timothy Mooney",
    "position": "Office Manager",
    "salary": "$136,200",
    "start_date": "2008/12/11",
    "office": "London",
    "extn": "7580"
  },
  {
    "name": "Jackson Bradshaw",
    "position": "Director",
    "salary": "$645,750",
    "start_date": "2008/09/26",
    "office": "New York",
    "extn": "1042"
  },
  {
    "name": "Olivia Liang",
    "position": "Support Engineer",
    "salary": "$234,500",
    "start_date": "2011/02/03",
    "office": "Singapore",
    "extn": "2120"
  },
  {
    "name": "Bruno Nash",
    "position": "Software Engineer",
    "salary": "$163,500",
    "start_date": "2011/05/03",
    "office": "London",
    "extn": "6222"
  },
  {
    "name": "Sakura Yamamoto",
    "position": "Support Engineer",
    "salary": "$139,575",
    "start_date": "2009/08/19",
    "office": "Tokyo",
    "extn": "9383"
  },
  {
    "name": "Thor Walton",
    "position": "Developer",
    "salary": "$98,540",
    "start_date": "2013/08/11",
    "office": "New York",
    "extn": "8327"
  },
  {
    "name": "Finn Camacho",
    "position": "Support Engineer",
    "salary": "$87,500",
    "start_date": "2009/07/07",
    "office": "San Francisco",
    "extn": "2927"
  },
  {
    "name": "Serge Baldwin",
    "position": "Data Coordinator",
    "salary": "$138,575",
    "start_date": "2012/04/09",
    "office": "Singapore",
    "extn": "8352"
  },
  {
    "name": "Zenaida Frank",
    "position": "Software Engineer",
    "salary": "$125,250",
    "start_date": "2010/01/04",
    "office": "New York",
    "extn": "7439"
  },
  {
    "name": "Zorita Serrano",
    "position": "Software Engineer",
    "salary": "$115,000",
    "start_date": "2012/06/01",
    "office": "San Francisco",
    "extn": "4389"
  },
  {
    "name": "Jennifer Acosta",
    "position": "Junior Javascript Developer",
    "salary": "$75,650",
    "start_date": "2013/02/01",
    "office": "Edinburgh",
    "extn": "3431"
  },
  {
    "name": "Cara Stevens",
    "position": "Sales Assistant",
    "salary": "$145,600",
    "start_date": "2011/12/06",
    "office": "New York",
    "extn": "3990"
  },
  {
    "name": "Hermione Butler",
    "position": "Regional Director",
    "salary": "$356,250",
    "start_date": "2011/03/21",
    "office": "London",
    "extn": "1016"
  },
  {
    "name": "Lael Greer",
    "position": "Systems Administrator",
    "salary": "$103,500",
    "start_date": "2009/02/27",
    "office": "London",
    "extn": "6733"
  },
  {
    "name": "Jonas Alexander",
    "position": "Developer",
    "salary": "$86,500",
    "start_date": "2010/07/14",
    "office": "San Francisco",
    "extn": "8196"
  },
  {
    "name": "Shad Decker",
    "position": "Regional Director",
    "salary": "$183,000",
    "start_date": "2008/11/13",
    "office": "Edinburgh",
    "extn": "6373"
  },
  {
    "name": "Michael Bruce",
    "position": "Javascript Developer",
    "salary": "$183,000",
    "start_date": "2011/06/27",
    "office": "Singapore",
    "extn": "5384"
  },
  {
    "name": "Donna Snider",
    "position": "Customer Support",
    "salary": "$112,000",
    "start_date": "2011/01/25",
    "office": "New York",
    "extn": "4226"
  }
]</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @kabus202!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4869). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4869)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by ituhin** [comment]
yes. something similar for me. working on a chat module and when I get into the room which has some messages (i scroll down automatically), i see a black screen first, then the screen loads sometime it scroll down after that but most of the times it does not.

from xcode debugger - 
2015-12-27 21:45:12.778 myApp[599:88735] -[WebActionDisablingCALayerDelegate setBeingRemoved:]: unrecognized selector sent to instance 0x15d75180
2015-12-27 21:45:12.780 myApp[599:88735] *** WebKit discarded an uncaught exception in the webView:willRemoveScrollingLayer:withContentsLayer:forNode: delegate: <NSInvalidArgumentException> -[WebActionDisablingCALayerDelegate setBeingRemoved:]: unrecognized selector sent to instance 0x15d75180
-------

i have something like 
$scope.$on('$ionicView.enter', function() {
$timeout(function() {
        footerBar = document.body.querySelector('#userMessagesView .bar-footer'); //console.log(footerBar);
        scroller = document.body.querySelector('#userMessagesView .scroll-content'); //console.log(scroller);
        txtInput = angular.element(footerBar.querySelector('textarea')); //console.log(txtInput);
      }, 0);
});

also i have this after the messages are loaded....
$timeout(function() {
                viewScroll.scrollBottom();
            }, 10);


hope this helps.

it happens only in ionic 1.2.1... works fine in 1.1.1
switching back to 1.1.1 for now.

**Comment by freiserg** [comment]
i have the same problem with native scroll.

You can update to 1.2.1 and set  
```
.config(function($ionicConfigProvider) {
    $ionicConfigProvider.scrolling.jsScrolling(true);
})
```

or add class:
```
.scroll-content {
    overflow-y: auto !important;
}
```

@mlynch Can it be fixed in 1.2.2?

Thank you.

**Comment by mlynch** [comment]
Kind of a lesser of two evils situation. Toggling overflow-scroll: hidden causes a flicker, so I disabled that for now. The alternative is to actively block scroll so I'm looking into that but I'd rather kill the flicker at the expense of scrolling happening.

**Comment by mlynch** [comment]
Okay, just pushed several fixes for this, can you try master and let me know how it works?

**Comment by ituhin** [comment]
@mlynch 
u mean with this - https://github.com/driftyco/ionic/blob/master/release/js/ionic.bundle.js  ?
that looks like 14 days old ! or do I need to setup something entirely from master !

**Comment by ituhin** [comment]
@mlynch 
i checked with 1.2.4 release.... and i still see a black screen just before it navigates to another page, for a sec.
but if i go back and navigate again, that black screen do not appear. looks like it comes only first time, (rare case 2nd time). but the errors in the console are gone. if i go back to ionic 1.1.1 black screen never appears. 

i also tried with 
.config(function($ionicConfigProvider) {
    $ionicConfigProvider.scrolling.jsScrolling(true);
}) with 1.2.4 but output is same.
