### ISSUE TITLE
Uncaught This view has already been destroyed

### ISSUE THREAD

**Issue by russli1993** [driftyco/ionic#5277]
I am currently work an app using ionic2@beta, I encountered this error when I try to do nav.setRoot(newPage) in a page to transition to a new navigation root from an existing navigation tree. "Uncaught This view has already been destroyed!".  Giving more context of the problem, I already have a few past views on the navigation stack. These are navigated by using nav.push(nextpage). Apparently when calling setRoot will remove all the previous pages. However when ionic tries to remove the first page on the stack, it throws the above error. Anyone know how to solve this?

**Comment by adamdbradley** [comment]
What alpha version are you using, have you tried the latest? We did fix a error like that recently.

**Comment by Luchillo** [comment]
In alpha 51 the error existed, in alpha 53 the error was fixed.

**Comment by slippyC** [comment]
I tried alpha 53 and error still remains...

**Comment by adamdbradley** [comment]
@slippyC @russli1993 Would either of you be able to provide an example of how you create this issue? I'm unable to replicate it in the latest versions. Thanks

**Comment by Luchillo** [comment]
Are you sure you updated to alpha.53? having the package.json with alpha.53 doesn't guarantee that node_modules have installed the alpha.53, try npm update.

**Comment by raffaeler** [comment]
I have the alpha.51 installed with
npm install -g ionic@beta
as suggested in the docs I could found

how am I supposed to install alpha.53?

BTW, as a workaround I patched the angular file:
<app>\node_modules\angular2\src\facade\exception_handler.js
and commenting these around row 78
        //if (this._rethrowException)
        //    throw exception;

Is there a roadmap/timeframe for the beta?
TIA,
Raf

**Comment by mhartington** [comment]
@raffaeler So `npm i -g ionic@beta` is our cli package, not the version of the framework.


Just to make sure, you can just update your package.json to match what we currently have in out app base.

https://github.com/driftyco/ionic2-app-base/blob/master/package.json

Once that is updated, you should be able to run `npm install` from inside your project to update it's dependencies.

**Comment by brandyscarney** [comment]
Here are some more docs on the different npm packages the ways to update each version: http://ionicframework.com/docs/v2/resources/using-npm/

**Comment by russli1993** [comment]
@adamdbradley Hi, thanks so much for the response, I updated to 53, the error is fixed. Thanks so much.

**Comment by raffaeler** [comment]
thank you, headache even in comparison to "dll hell", but thank u all

**Comment by adamdbradley** [comment]
Great, thanks @russli1993

**Comment by slippyC** [comment]
The views are working now!.  Thanks guys.  There is still an error getting thrown in Chrome, but it does work.

**Comment by slippyC** [comment]
Just tried something.  if you have swipe-back-enabled="true" under your <ion-nav> tag you will get stuck.  Don't think it is obeying that flag and destroying view.  This is more of a heads up, because that really doesn't matter to me.

Thanks again...

**Comment by ThulaniMtetwa** [comment]
https://stackoverflow.com/a/45097885/3665595
