### ISSUE TITLE
Ionic2 - nav.setRoot(Component) - Works only first time, unable to navigate after, no errors reported

### ISSUE THREAD

**Issue by tonyawad88** [driftyco/ionic#5883]
#### Short description of the problem:
I am developing an app with Ionic2. I have App.ts as the parent, Welcome.ts as a child page and Featured.ts as a child page as well. I have firebase integrated with the app. Rootpage is first set to Welcome. 
```
this.rootPage = Welcome;
```

Step 1: I click a button on Welcome to authenicate with Google, once onAuth is called, I set ``` this.nav.setRoot(Featured);``` All works fine up to now. I get to the Featured page which enables a sidemenu with different pages and i am able to navigate to all of them no problem.

Step 2: Featured enables a sidemenu from App.ts/html, in there I have a logout button that calls unauth.
Unauth does some Firebase unauth and then:
```
this.menu.close();    
let nav = this.app.getComponent('nav');    
nav.setRoot(Welcome); 
```
Step 3: Login again same as in step 1. All is fine up to now.

Step 4: Open side menu, selects any of the pages from the sidemenu, navigation doesn't occur. sidemenu closes but page remain the same, navbar icon button disappear and no navigation occurs.
openPage code: 
```
  openPage(page) {
    //1. Loop through and set active attribute to False if it doesn't match.
    //   Set to True if it matches page title
    for(var i = 0; i < this.NavPages.length; i++) {
      if(this.NavPages[i].title == page.title) this.NavPages[i].active = true;
      else this.NavPages[i].active = false;
    }
    for(var i = 0; i < this.ActivityPages.length; i++) {
      if(this.ActivityPages[i].title == page.title) this.ActivityPages[i].active = true;
      else this.ActivityPages[i].active = false;
    }
    for(var i = 0; i < this.PreferencesPages.length; i++) {
      if(this.PreferencesPages[i].title == page.title) this.PreferencesPages[i].active = true;
      else this.PreferencesPages[i].active = false;
    }

    //2. close the menu when clicking a link from the menu
    this.menu.close();
    //3. navigate to the new page if it is not the current page
    let nav = this.app.getComponent('nav');
    nav.setRoot(page.component);
  }
```

#### What behavior are you expecting?
I am expecting navigation to continue to occur, similar to what happens in step 1.

**Steps to reproduce:**
Steps to reproduce included above.

```
Code included above.
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 No error is being thrown unfortunately. I don't see any erros in the console logs.

**Which Ionic Version?** 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
```
Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
ios-deploy version: 1.8.2 
ios-sim version: 5.0.3 
OS: Mac OS X El Capitan
Node Version: v0.12.7
Xcode version: Xcode 7.2.1 Build version 7C1002 
```

Thank you.

**Comment by tonyawad88** [comment]
I noticed the following: 2 ion pages are present at once in the dom.
<img width="521" alt="screen shot 2016-03-18 at 3 34 03 pm" src="https://cloud.githubusercontent.com/assets/3638322/13889822/f8bb45a4-ed1e-11e5-93f1-77d1bb5c0366.png">

The one I navigated to is "explore" which has a lower z-index(92) than the "featured" page. Therefore I should be on explore but the "featured" is overlayed on top of "explore" with a z-index of 93.

**Comment by jorchg** [comment]
I'm experiencing the same issue but in my case I can't even get redirected after login.

If I'm already logged and land in the login view, `nav.setRoot(TabsPage)` is executed perfectly.

But if I log-in with facebook after getting the user probile `nav.setRoot(TabsPage)` is doing nothing. Moreover, `nav.push(TabsPage)` is also doing nothing, but if I do `nav.push(Main)` where Main is one of my tabs, is executing correctly, but I don't have tabbar and a back button appears, obviously.

Also if I do `nav.setRoot(Main)` it works correctly, but I land in a tab without tabbar and with back button.

**Comment by jorchg** [comment]
I add some information. I saw in the docs that `setRoot` return a promise, so I did this:

```
this.nav.setRoot(TabsPage)
  .then(data => {
      console.log(data);
  }, (error) => {
      console.log(error);
  })
```

This throws `true` when I land on the login page and I'm already logged, but throws nothing when I login with facebook, so it seems that the promise is never resolved.

**Comment by jorchg** [comment]
Ok, another update. If you go to the core of Ionic2 to components/nav/nav-controller.js in the function setPages which is called from setRoot the callback of the transition is never been executed.
If you follow the flow of functions called: setRoot -> setPages -> _transition -> _render -> _postRender

In the _render function:

```
this.loadPage(enteringView, null, opts, function () {
    if (enteringView.onReady) {
        // this entering view needs to wait for it to be ready
        // this is used by Tabs to wait for the first page of
        // the first selected tab to be loaded
        enteringView.onReady(function () {
            enteringView.loaded();
            _this._postRender(transId, enteringView, leavingView, isAlreadyTransitioning, opts, done);
        });
    }
    else {
        enteringView.loaded();
        _this._postRender(transId, enteringView, leavingView, isAlreadyTransitioning, opts, done);
    }
});
```

My code enters in `enteringView.onReady` and the callback is never executed.

If I just call the `_postRender` method before waiting for `enteringView.onReady` my app works fine, but It's so dirty.
The problem seems to be waiting for the page of the tab to be ready. I think it never gets ready or never acquire fine the ready state.

Could be this something with my code? Or is likely to be a bug?

Thank you!

**Comment by privetr** [comment]
I have the same problem with Google or Facebook auth

**Comment by tonyawad88** [comment]
@privetr this seems to have been fixed with beta4. Can you please check ? Mine is working fine now.

**Comment by tonyawad88** [comment]
@jorchg Can you check as well ? when you get a chance :)

**Comment by jgw96** [comment]
Hello all! As it looks like this was fixed in beta.4 i will be closing this issue, but if you are still having this issue feel free to comment!

**Comment by tlaverdure** [comment]
I am still having this issue. I can't get the nav to push or setRoot to my TabsPage after a Facebook login promise. 

```
Cordova CLI: 6.1.1
Gulp version:  CLI version 1.2.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.4
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
ios-deploy version: 1.8.5
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v5.9.1
Xcode version: Xcode 7.3 Build version 7D175
```

**Comment by daveshirman** [comment]
I also am experiencing the situation where if I call nav.setRoot(x), the new page doesn't actually appear.  Yet, if I focus an input field in the current page, it disappears and shows the correct page.

**Comment by tonyawad88** [comment]
@daveshirman are you using tabs to navigate around ? It might be related to tabs, my issue was related to sidemenu. However they both use the navcontroller, not sure why it would work for me and not for you.. Maybe produce a plunker or open a new issue and the ionic team will be able to help out.

**Comment by HereThereBeMonsters** [comment]
I was having the same issue : `nav.setRoot(MyComponent)` did not seem to do anything. I was running the app in Android using `--live-reload`, and there were warnings about some events not being fired :
```
0     195445   log      deviceready has not fired after 5 seconds.
1     195457   log      Channel not fired: onDOMContentLoaded
```

I also could not test the code in the browser because it's about displaying a certain page when the device goes offline.

So I finally tried to run my code in Android, but without the live reload, and it works fine.

So, there is something about the live reload mode that is preventing it from working. Using Beta4 as my dependency, and the CLI version 2.0.0-beta25.

**Comment by SoaringTiger** [comment]
I have the issue like this: [Tabs persist after logging out of app, start stacking on log in](https://forum.ionicframework.com/t/tabs-persist-after-logging-out-of-app-start-stacking-on-log-in/46321)

**Comment by jorchg** [comment]
I'm still experiencing the issue I described. I completely forgot, and after a ionic update it stopped working, so I just modified it again as described in my latest post in this thread.

**Comment by malvarezhcr** [comment]
Hi Everyone. Did anyone find a fix for this? I am currently using Ionic 2@beta.9 and the problem is still present!

**Comment by beck24** [comment]
I too seem to have run into this

**Comment by TheMadBug** [comment]
I find the problem is less severe in beta.9 (but still consistently reproducible).
In beta.10 subsequent setRoots fail to render properly, much worse than beta9 - even when set within a NgZone.run
I'll see if I can find a similar open issue, if not I'll raise a new one.

**Comment by daveshirman** [comment]
I found that calling it from my app.ts seems to work reliably.  Calling it from any other page seems to fail.
Additionally, if I am not on a root page, like 3 pages deep, I also call nav.popToRoot() after the setRoot method, which works:

```
this.nav.setRoot(xxxx).then(() =>{
    this.nav.popToRoot();
    //....
});
```

**Comment by scorpnode** [comment]
Why is this issue closed? Navigation seems really broken. If i push a page with forms in it it wont work either.

**Comment by daveshirman** [comment]
Also breaks when there's a modal window showing too.

**Comment by nicopeeters** [comment]
Hi, this is still occurring to me in 2.0.0-beta.10. I'm getting a blank screen after calling NavController.setRoot. Only occurring on iOS devices

**device info:** 
- model: iPad5,4
- iOS version: 8.3

**Comment by pratyushsharma** [comment]
I am facing this issue in  2.0.0-beta.10. I'm not able to navigate by NavController.setRoot. 
my code looks like this:
    this.nav.setRoot(somepage).then(() =>{
     this.nav.popToRoot();
     });

**Comment by sunnypatel** [comment]
CLI v2.0.0-beta.32.

Still having issues with 
`this.nav.setRoot(ListPage) `
from hello-ionic.ts of the starter tutorial app. 

I wanted to try FB login which has been made effortless with v2 tutorial.

Anyone else?

**Comment by HamzaLJ** [comment]
Having the same issue here!

**Comment by jgw96** [comment]
Hello everyone, if someone could provide a plunker that demonstrates this issue that would be awesome. Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by amsoftgit** [comment]
I am using 
import {Nav} from 'ionic-angular';
instead of
import {NavController} from 'ionic-angular';

Resolved my issue. Hope that helps anyone.

**Comment by jorchg** [comment]
Sorry for not answering, I was on Holidays 💃 

My problem seems to have been related to cordova-plugin-facebook4 https://github.com/jeduan/cordova-plugin-facebook4

When I updated my project to beta.10 and started using Facebook wrapper from ionic-native the problem just stopped. Very strange, taking into account that the wrapper uses the same plugin.

Thank you very much!

**Comment by jgw96** [comment]
No problem, glad its fixed for you!

**Comment by joshgarwood** [comment]
Hey @jgw96 !  Unfortunately this still seems to be a problem for me in Beta 10.  You can see this in the plnkr below.  Effectively, I have a login modal that sets the root to a "Tabs" page once successfully logged in.  From a page in the "Tabs" i have a "Logout" button, which fires an event that is consumed in app.ts.  In app.ts I try to set the root to the "LoginPage", but nothing seems to happen.  In looking at the DOM while clicking "logout" I can see things firing, and the login page exists underneath the tabs, but the navigation just doesn't seem to occur.  Any ideas?

http://plnkr.co/edit/n6jCzspnEcjQbl9KF10F

Thanks for your time!

**Comment by Abdiliban** [comment]
Having the same issue here. **2.0.0-beta.11**

**Comment by itemir** [comment]
Same here, this seems to have re-occurred in 2.0.0.beta.11 

Pushing to a tabs page (nav.push or nav.setRoot) does not work. This was working in 2.0.0.beta.10.

**Comment by itemir** [comment]
I filed a new issue for this #7593. Applicable to 2.0.0-beta.10 and 11, possibly others.

**Comment by Troknus** [comment]
I have the same problem with beta 11.
Navigation seems to work well until this.nav.setRoot(xxx) is called. After that, navigation works randomly... When pushing a new page, sometimes nothing happens : the view stay on the current page instead of the new one. When poping, navigation seems other times to pop twice.
Everything seems to be correct with the NavController object and everything fires normally. But it seems there is confusion in the DOM : values of z-index properties for ion-page tags are wrong in these cases, so that the wrong page stays above.

**Comment by daveshirman** [comment]
I see exactly the same behaviour as @Troknus regarding double page popping and DOM confusion.  

Also first time setRoot, then upon next navigation, the initial root page flickers up, as if it wasn't completely unloaded before.

**Comment by Danjavia** [comment]
I have the issue too I try to adding show-page class manually and function but is not good solution

**Comment by joewoodhouse** [comment]
I'm seeing the same behaviour as @Troknus too.

**Comment by mariohmol** [comment]
Guys, having same problem as @jorchg said.. considering the tabs error.. it just push to tabs after second time it calls (seems that the push occurs but the current page still on top)

after login if I try to push to tabs view but do not wotk.. if i push to a page that is supposed to be in a tab.. it works..  here is the project

* https://github.com/mariohmol/ionic2-meteor-messenger

**Comment by schaergeek** [comment]
I have the same problem as @Troknus

**Comment by mariohmol** [comment]
@schaergeek updated to beta 11 and it worked.. here is the example https://github.com/mariohmol/ionic2-meteor-messenger-password

**Comment by movrack** [comment]
I did thumbs up on Troknus post but it's a real problem. We are not allowed to move in production with this bug.
(We are working in beta 11 as Troknus).

**Comment by rcjsuen** [comment]
I took a look at the [plnkr](http://plnkr.co/edit/n6jCzspnEcjQbl9KF10F) by @joshgarwood. The event publishing seems to be the issue? If instead of publishing the authentication event to have MyApp do the work, you instead set the root via the NavController instance within TabPage, then it works. Trying to set the root via the event listener in MyApp doesn't. So it seems to me like an issue with the different NavController instances that are being injected...? I'm not sure how the DI is supposed to work here but I feel like the consumer shouldn't have to care about which instance of NavController is injected. If I call setRoot(*) then things should just work, right?

Regarding the Z-index problem that @Troknus is talking about, you all may be interested in issue #8042. Though in that case setRoot(*) is not being called at all.

**Comment by rcjsuen** [comment]
Actually, I just read @jgw96's [comment](https://github.com/driftyco/ionic/issues/7652#issuecomment-239200902) and it seems you're not supposed to use random NavController instances...?

Still, that doesn't change the fact that there is a bug with the Z-indices.

**Comment by victorcarvalhosp** [comment]
same problem here with beta11...

**Comment by rcjsuen** [comment]
Does anyone have a different plnkr that will reproduce the DOM getting confused or pages flickering? The plnkr by @joshgarwood doesn't include pushes or pops.

**Comment by Vanclief** [comment]
@rcjsuen  Had the same problem in Beta10 & Beta11, I figured out this workaround. Not sure if setRoot is working as intended but this works for now.

Not working

```
  private initializeApp(): void {
    this.platform.ready().then(() => {

      firebase.auth().onAuthStateChanged(user => {
        if (user) {
          this.nav.setRoot(TabsPage);
        } else {
          this.nav.setRoot(LoginPage);
        }
      });

      StatusBar.styleDefault();
    });
  }
}
```



Working
 ```
 private initializeApp(): void {
    this.platform.ready().then(() => {

      firebase.auth().onAuthStateChanged(user => {
        if (user) {
          this.setRoot(TabsPage);
        } else {
          this.setRoot(LoginPage);
        }
      });

      StatusBar.styleDefault();
    });
  }

  private setRoot(newRootPage: any){
    this.rootPage = newRootPage;
  }
}
```

**Comment by Peter-Piper** [comment]
@Vanclief Have same problem - but even this solution you've proposed didn't work for me. 
My code was as yours to begin with - then I tried upgrading to ionic 2 rc0 and angular 2.0.1, but that didn't work well with firebase (nor angularfire), so I rolled back to:

`
@angular/common": "2.0.0-rc.4",
    "@angular/compiler": "2.0.0-rc.4",
    "@angular/core": "2.0.0-rc.4",
    "@angular/forms": "^0.2.0",
    "@angular/http": "2.0.0-rc.4",
    "@angular/platform-browser": "2.0.0-rc.4",
    "@angular/platform-browser-dynamic": "2.0.0-rc.4",
    "@angular/router": "^2.0.0-rc.2",
    "firebase": "^3.3.0",
    "ionic-angular": "2.0.0-beta.11",
    "ionic-native": "1.2.2",
`
deleted node_modules/ did npm install and now I'm facing this problem.

**Comment by Vanclief** [comment]
@Peter-Piper 

I did not update, but I kept having some problems that went away once I upgraded to RC0. For one of my projects Im also using firebase and had some problems updating but now everything is working.  

I do not use AngularFire, but this tutorial covers it: https://playcode.org/getting-started-with-ionic-2-rc0-firebase-3-angularfire-2/

**Comment by Peter-Piper** [comment]
@Vanclief 

Thanks, I did already try this approach - and it did work. But the fact that I have to do hacks in a node module combined with ionic RC_0 crashing when watching files when doing ionic serve made me abort upgrading and stick to the older version.

Anyways, I did solve the issue mentioned above where setting root page in a callback never works unless it has been set before, by checking if firbase.auth.currentUser is set and then setting the rootPage

```javascript
        const page = firebase.auth().currentUser ? TeamPage : LoginPage;
        this.setRoot(page);

        firebase.auth().onAuthStateChanged(user => {
            // If there's a user take him to the Teams page otherwise send him to LoginPage
            const page = user ? TeamPage : LoginPage;
            this.setRoot(page);
        });
```

and then doing a check in the setRoot method so it doesn't navigate to the same page twice.

This is also a hack and doesn't address the underlying problem. Unfortunately I don't have the time to go in to an in depth investigation of the issue the next week.

**Comment by henry74** [comment]
This is still a problem.  Using this.nav.push(...) works fine, but using this.nav.setRoot(...) does not work after the first time.  Here's my ionic info:

~~~
Your system information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS: Distributor ID:	Ubuntu Description:	Ubuntu 16.04.1 LTS 
Node Version: v4.6.0
~~~
From package.json
~~~
  "dependencies": {
    "@ionic/storage": "^1.0.3",
    "firebase": "^3.4.1",
    "ionic-angular": "^2.0.0-rc.0",
    "ionic-native": "^2.2.2",
    "ionicons": "^3.0.0"
  },
~~~

**Comment by daveshirman** [comment]
@jgw96 Why is this closed? Clearly this is an open case as setRoot is not working properly.

**Comment by OyebisiJemil** [comment]
@daveshirman, i was facing the same problem, it is not a navigation problem, but here is how i solved it.

in my app.ts is have this 

firebase.initializeApp(config);

    platform.ready().then(() => {
      firebase.auth().onAuthStateChanged((user) => {
        if (user) {
          // If there's a user take him to the TabsPage page.
          this.rootPage = TabsPage;
        } else {
          // If there's no user logged in send him to the LoginPage
          this.rootPage = LoginPage;
        }
      });
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      StatusBar.styleDefault();
    });

the if statement above is saying  // If there's a user SET THE ROOTPAGE TO  TabsPage page.
and else it should remain in the LoginPage, you will note that if you use normal firebase login method, the if part will execute (i.e it will navigate to the rootPage, but when using Facebook the else part will execute (i.e it stays on the LoginPage

I solved it like this.
 facebookLogin() {


    Facebook.login(['email']).then((result=>{
      let credentials = firebase.auth.FacebookAuthProvider['credential'](result.authResponse.accessToken)
     
       return firebase.auth().signInWithCredential(credentials);
    })).then((user)=>{
        //alert(firebase.auth().currentUser.uid);
        this.userProfileRef.child(firebase.auth().currentUser.uid).set({
          id:firebase.auth().currentUser.uid,
          email: user.email,
          displayName:user.displayName,
          profilePictureURL:user.photoURL
        });
        
       this.navCtrl.setRoot(TabsPage);
    }).catch((error)=>{
      alert(error);
    })
  }


what happened in the code above is that,
 1st you need to login to facebook, which i did with 
**Facebook.login(['public_profile']).then((result=>**

2nd you need to set a credentials that will help you login to the firebase using the accessToken sent to you by Facebook login result which is what i did here 
  **let credentials = firebase.auth.FacebookAuthProvider['credential'](result.authResponse.accessToken);**
3rd you need to login to firebase with credentials you set, which is what i did here 
**return firebase.auth().signInWithCredential(credentials);**
NOTE: this the exact reason why your  this.navCtrl.setRoot(TabsPage); did not work (because the user is yet to login on firebase.

so you can now navigate to the rootPath at the then() path of the code.

and please kindly make sure you your facebook appId and appSecrete is configured on firebase>authentication>facebook panel.

HOPE THIS HELP 
okLogin() {


    Facebook.login(['email']).then((result=>{
      let credentials = firebase.auth.FacebookAuthProvider['credential'](result.authResponse.accessToken)
     
       return firebase.auth().signInWithCredential(credentials);
    })).then((user)=>{
        //alert(firebase.auth().currentUser.uid);
        this.userProfileRef.child(firebase.auth().currentUser.uid).set({
          id:firebase.auth().currentUser.uid,
          email: user.email,
          displayName:user.displayName,
          profilePictureURL:user.photoURL
        });
        
       this.navCtrl.setRoot(TabsPage);
    }).catch((error)=>{
      alert(error);
    })
  }


what happened in the code above is that,
 1st you need to login to facebook, which i did with 
**Facebook.login(['public_profile']).then((result=>**

2nd you need to set a credentials that will help you login to the firebase using the accessToken sent to you by Facebook login result which is what i did here 
  **let credentials = firebase.auth.FacebookAuthProvider['credential'](result.authResponse.accessToken);**
3rd you need to login to firebase with credentials you set, which is what i did here 
**return firebase.auth().signInWithCredential(credentials);**
NOTE: this the exact reason why your  this.navCtrl.setRoot(TabsPage); did not work (because the user is yet to login on firebase.

so you can now navigate to the rootPath at the then() path of the code.

and please kindly make sure you your facebook appId and appSecrete is configured on firebase>authentication>facebook panel.

HOPE THIS HELP

**Comment by daveshirman** [comment]
@OyebisiJemil Thanks for your long explanation of what you did. But I meant I was having the same problem conceptually in that setRoot doesn't work properly, not with using facebook or anything.  Thanks again though.  This issue shouldn't be closed, unless there is another open with the same description.

**Comment by joshuaohana** [comment]
I'm also hitting this issue with very similar circumstances. In my case switching to push(view) instead of setRoot(view) resolved the problem and doesn't really jack with my app flow.

**Comment by lisaiceland** [comment]
I'm still facing same issue as of today in latest build:

logOut() {
  this.authData.logoutUser().then(() => {
    this.nav.setRoot(LoginPage);
  });
}

does NOT work. Plz help. Thnx. Lis

**Comment by dejancencelj** [comment]
Use push insted of setRoot...

**Comment by daveshirman** [comment]
@jgw96, @adamdbradley  this is still a major issue. Please reopen it and assign a milestone. Many people are having this issue and is essential functionality for an app.

**Comment by niallr12** [comment]
@dejancencelj that is not a solution to this issue. 

@lisaiceland to get around this problem I followed this suggestion:
https://forum.ionicframework.com/t/cant-access-rootnav-after-upgrade-to-beta-11/59889/15?u=niallr

**Comment by manucorporat** [comment]
@niallr12 @daveshirman is this still an issue in RC3?

**Comment by niallr12** [comment]
@manucorporat I am unsure if this is a problem in RC3 but I don't see a fix for it in the changelog. I am happy with my fix and feel it is an overall better approach anyways. 

I can test for you in RC3 if you like.

**Comment by manucorporat** [comment]
@niallr12 well, I never was able to reproduce this particular problem. But I have spend weeks hardening  NavController, with tons of little fixes and tests. Like this one: [Worst Case](https://github.com/driftyco/ionic/blob/master/src/components/nav/test/worst-case/app-module.ts) that stresses the navigation stack with a crazy flow.

**Comment by niallr12** [comment]
@manucorporat I can still replicate the problem in rc3. In my particular case it doesn't seem to be dismissing the current view when I am setting root. If I dismiss the current view and then set root it works fine. Pushing the view works completely fine.

**Comment by tomaszczechowski** [comment]
Hey, 

I'm not sure whether my answer will help anybody since I have not read all previous messages, but when I encountered on such issue in my project I resolved it by referring to parent navigation stack, for that reason I was able to move back to welcome page e.g:

Welcome page (root page)
```javascript
gotoFeature(): void {
  this.navCtrl.push(feature);
}
```
Feature page (**with tabs**)
```javascript
logout(): void {
  this.navCtrl.parent.parent.pop() //  back to welcome
}
``` 
It needs to be handled in that way since tabs have their own navigation stack what means that every use of **setRoot** in tabs navigation object level will redirect to different page but tabs block in footer would be still visible.

**Comment by anilcancakir** [comment]
Why is this issues closed? I have same problem. I'm using setRoot function in my sample provider. App setRoot and changed page but navigation (menu) is disabled when finished.

It's my code in provider
`private _leaveGroup(user: modelUser, room: modelRoom): Promise<any> {
    return new Promise((resolve, reject) => {
      let loading = this.loadingCtrl.create({dismissOnPageChange: false});
      loading.present();

      this.ref.child(room.id).child('users').child(user.id).remove()
        .then(() => this.navCtrl.setRoot(PageDashboard))
        .then(() => loading.dismiss())
        .then(() => resolve())
        .catch(err => loading.dismiss().then(() => reject(err)));
    });
  }`

It's my info
`--------------------------------

Your system information:

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.45
ios-deploy version: 1.9.0
ios-sim version: 5.0.9
OS: Mac OS X Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62


--------------------------------`

**Comment by gchandrapati** [comment]
I had same problem. However after I ensured that at any given time if only setrroot statement is executed everything works perfect. But for various reason if multiple setroot statements are executed at any given time, Ionic is creating multiple pages dues to which the navigation is getting hanged in my case.

**Comment by joshuaohana** [comment]
Seems this issue mutated to something stranger in RC4. Same type of issue except that when setting root now from the exampled login page to a menu/dashboard the login page remains in the view stack which displays the back button in the header, causing all kinds of mayham

**Comment by siteslave** [comment]
I create event for logout.

```
// app.component.ts
events.subscribe('logout', () => {
  localStorage.removeItem('token');
  this.rootPage = LoginPage;
 });
```

now logout:

```
// pages/home/home.ts
  logout() {
    this.events.publish('logout');
  }
```

**Comment by pisix** [comment]
Hi Everyone. Did anyone find a fix for this? I am currently using Ionic 2.0.0-rc.4 and the problem is still present!

**Comment by Cardosao** [comment]
Hi,

`
//import these classes
import { Component, ViewChild } from '@angular/core';
import { Platform, MenuController, Nav } from 'ionic-angular';

export class MyApp {
  //Set this property
  @ViewChild(Nav) nav: Nav;

  //implement this method, and works perfectly
  private openPage(page: any): any {
    //validate token 
    this.loggedIn = this.service.canActivate();
    if (!this.loggedIn) {
      //not logged 
      this.nav.setRoot(LoginPage);
    } else {
      //logged
      this.nav.setRoot(HomePage);
    }
    this.menuCtrl.close();
  }
`
Hugs!

**Comment by siteslave** [comment]
```
import {
  NavController,
  LoadingController,
  App,
} from 'ionic-angular';

//=====================//
 logout() {
    localStorage.removeItem('token');
    let nav = this.app.getRootNav(); 
    nav.setRoot(LoginPage);
  }
```

**Comment by leroygumede** [comment]
Has anyone found at least a workaround to this ?

**Comment by Mokto** [comment]
Same issue as @joshuaohana.

If I do setRoot BEFORE facebook login, everything works as expected.
If I do setRoot AFTER facebook, I get the same behaviour as @joshuaohana.

Thanks.

**Comment by ly-dev** [comment]
create event for logout works. 

also, find below a detail explanation about nav with another working solution

https://webcake.co/exploring-nav-hierarchy-in-the-ionic-2-tabs-page/

most valuable piece of the code pasted below.

import { App } from 'ionic-angular';
...
  constructor(private _app: App) {}

  logout() {
        ...

        // Now I'll access the root NavController for the app,
        // and use that to reset the nav stack

        const root = this._app.getRootNav();
        root.popToRoot();

        // since I only have two items in the root NavController,
        // I could also have run root.pop() instead
  }
...

**Comment by mtraut** [comment]
Maybe some of you made the same mistake as me:

I used navigation via "setRoot" but missed that at the same time the binding "[root]=.." is still available on the HTML template. Bringing the two infos in synch again fixed my problem. In this case i removed the model binding and managed the root only via API.

Regards, Michael

**Comment by theomathieubhvr** [comment]
Hi guys,

@ly-dev solution worked for me. I just did `this._app.getRootNav().setRoot(EntryPage);` and it works.

**Comment by AmitPoojary** [comment]
First, import Nav from ionic-angular, same place as navController
`import { App, NavController } from 'ionic-angular';`

then provide it in your constructor :
`constructor(public navCtrl: NavController, public appCtrl: App) `

now you can acces the rootnav:
`this.appCtrl.getRootNav().setRoot(YourComponent);`

**Comment by dragonfire1119** [comment]
@AmitPoojary That solution has not worked. When the user goes to multiple tabs. 

**Example**: Home tab with multiple pages. When the user clicks through to the multiple pages. Then doesn't go back but switches over to Account tab & then logs out it will stay on the Account tab until refresh.

I've figured out if the user clicks on the Home tab & doesn't go any further it will log the user out correctly.

I'm thinking it's all about getting to many tabs in the dom & `getRootNav` isn't going back that far when the user goes in to many pages.

**Comment by cperezvinsite** [comment]
I faced the same Issue, after the promise of facebook or google oauth i made a 
```javascript
this.navCtrl.setRoot(MyPageComponent);
```

but when this new component being loaded the touch event didn't works, by mistake i discovered if you touch some element like an input right after the promise and just before the transition is made, this problem wont happen, for this reason I assigned an ID to a input and just before the promise return I run this code
```javascript
$('#miIdOfInput').focus()
$('#miIdOfInput').click()
``` 

It works for me

**Comment by Ross-Rawlins** [comment]
This is still an issue.

**Comment by bobalazek** [comment]
I can also confirm that it's still an issue. It works fine when it's called directly as an event (`<button (click)="onClickSubmit()" ...>` for example), but not if it's inside a callback, that is triggered by an event emitter (if you have a child component, to which you want to send the callback from the parent).

**Comment by neo-split** [comment]
Yes, still an issue for me as Im using Tab's as the main landing page of application. By calling _navCtrl.setRoot() from any of the pages inside the tabComponent, only that page is set to rootPage but the tab interface at the bottom stays in place. 

![image](https://cloud.githubusercontent.com/assets/6942628/25726322/4931c434-312c-11e7-8063-2e0d7fa3b9ea.png)

**Comment by uiktiomasfeliz** [comment]
The right solution to this is:

`let _nav = this.app.getRootNav();
        _nav.setRoot(LoginPage);`

**Comment by inepali** [comment]
I also have similar problem on my new app, my application is working only first push to the device, where I make socket connection and perform some socket communication. I kill the app, disconnect from the from my development computer, re-run the application, I did not see no connectivity activity on server side. I have not implement uiktiomasfeliz recommendation, I will try that later today. But just an heads up.

**Comment by Navil** [comment]
Having the similar issue. I have a sidemenu inside my TabsPage and it is missing whenever I logout and afterwards login again. 
The strange part is: If i run two devices in the browser (serve -l) the device I did not activly logout at, works fine, while the menu is missing on the device, I performed the logout/login on. 
Also, when I refresh the page (I am still logged in from the old session), it works on both devices too.

Here are two images showing the issue:
![image](https://cloud.githubusercontent.com/assets/3436399/26318164/8598fab8-3f1a-11e7-9380-e12b57368dfc.png)

After the relog on the right (iOS) device:

![image](https://cloud.githubusercontent.com/assets/3436399/26318194/a473bdc4-3f1a-11e7-987c-845a5c56237c.png)

I did the logout/login on the iOS device (it doesn't matter, which one I take tho), and because of my onAuthStateChanged-Trigger, the other device is performing the relog too (in a correct way).

**Comment by alejandro-heredia-coderoad-com** [comment]
Yes. I also accomplished the same with:

`this.app.getRootNav().setRoot(SetupPage);`

However, it breaks the images paths on devices...

**Comment by pauleau** [comment]
(getRootNav) is deprecated and will be removed in the next major release. Use getRootNavById instead.

So... this error was never fixed and the previous patch is not working anymore.. :/

**Comment by arnoldparge** [comment]
`this.app.getRootNav().setRoot(LoginPage);`

This is not woking for me...

**Comment by skyserpent** [comment]
still an issue

**Comment by KrunchMuffin** [comment]
welp, 3.5.3 did not fix it for me.

**Comment by ashrfhassan** [comment]
iam using ionic 4 guys and still having this problem sidebar not working after setRoot();

i only use this :        this.navCtrl.setRoot(HomePage);

**Comment by FatehiAlqadasi** [comment]
I tried all solution here but still having this problem

**Comment by spidermay** [comment]
i solved like that

import App

import { IonicPage, NavController, Nav, App } from 'ionic-angular';

AND now use 

    const root = this.app.getRootNav();
    root.popToRoot();
    root.setRoot("LoginPage");

**Comment by alemdg** [comment]
Hello, i am testing a the hello world app on an iPhone4 and some others devices with Android.

Last Ionic and CLI version.

The main huge problem is with the iPhone, the call to setRoot is not working.

void onGoClick(){
// this line DOES NOTHING and no error is thrown.
    this.navCtrl.setRoot(HomePage);

}



regards.

**Comment by spidermay** [comment]
I think it is the way in which you are calling the routes, for example if you define like a text or like a object, whatever, 

if you want to avoid problems, call like a text ( "HomePage" ) and create this variable 

const root = this.app.getRootNav();

and call the following method

root.popToRoot();
root.setRoot("LoginPage");


import this object

import { IonicPage, NavController, NavParams, Nav, App } from 'ionic-angular';

constructor(
  public app: App
) {

first is the popToRoot and second define new root ;)

**Comment by alemdg** [comment]
@spidermay Thanks for the answer but still not working.

**I imported** 
import { IonicPage, NavController, NavParams, Nav, App } from 'ionic-angular';

**and executed**
const root = this.app.getRootNav();
root.popToRoot();
root.setRoot("HomePage");

**Comment by MT--** [comment]
I am seeing this on 3.7.1.

**Comment by FatehiAlqadasi** [comment]
Use the following code it must work or give you an error message

this.menu.close();
    this.nav.setRoot(HomePage).then(()=>{
      this.nav.popToRoot();
    }).catch(err=>{
      alert(err.toString());
    });

**Comment by alemdg** [comment]
Hi @FatehiAlqadasi, thanks. 
An error is thrown, here is the log.

> err: 
C@file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/main.js:7:21236
file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/main.js:7:21702
file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/main.js:7:21967
reduce@[native code]
O@file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/main.js:7:21927
format@file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/main.js:8:12952
transform@file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/main.js:8:14339
Ce@file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/main.js:3:23348
Ie@file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/main.js:4:1046
Te@file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/main.js:4:518
no@file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/main.js:4:5140
file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/main.js:42:25653
updateRenderer@file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/main.js:4:4409
Se@file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/main.js:4:328
We@file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/main.js:4:3041
Ge@file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/main.js:4:2439
Se@file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/main.js:4:336
detectChanges@file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/main.js:6:5799
_viewAttachToDOM@file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/main.js:17:22059
_transition@file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/main.js:17:23173
file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/main.js:17:19213
invoke@file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/polyfills.js:3:9288
onInvoke@file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/main.js:5:1143
invoke@file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/polyfills.js:3:9231
run@file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/polyfills.js:3:4458
file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/polyfills.js:3:14079
invokeTask@file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/polyfills.js:3:9972
onInvokeTask@file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/main.js:5:1047
invokeTask@file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/polyfills.js:3:9900
runTask@file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/polyfills.js:3:5153
o@file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/polyfills.js:3:2210
invoke@file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/polyfills.js:3:10986
err: 
C@file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/main.js:7:21236
file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/main.js:7:21702
file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/main.js:7:21967
reduce@[native code]
O@file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/main.js:7:21927
format@file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/main.js:8:12952
transform@file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/main.js:8:14339
Ce@file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/main.js:3:23348
Ie@file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/main.js:4:1046
Te@file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/main.js:4:518
no@file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/main.js:4:5140
file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/main.js:42:25653
updateRenderer@file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/main.js:4:4409
Se@file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/main.js:4:328
We@file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/main.js:4:3041
Ge@file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/main.js:4:2439
Se@file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/main.js:4:336
detectChanges@file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/main.js:6:5799
_viewAttachToDOM@file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/main.js:17:22059
_transition@file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/main.js:17:23173
file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/main.js:17:19213
invoke@file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/polyfills.js:3:9288
onInvoke@file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/main.js:5:1143
invoke@file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/polyfills.js:3:9231
run@file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/polyfills.js:3:4458
file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/polyfills.js:3:14079
invokeTask@file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/polyfills.js:3:9972
onInvokeTask@file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/main.js:5:1047
invokeTask@file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/polyfills.js:3:9900
runTask@file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/polyfills.js:3:5153
o@file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/polyfills.js:3:2210
invoke@file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/polyfills.js:3:10986
dispatchEvent@[native code]
handleTapPolyfill@file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/main.js:18:6423
pointerEnd@file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/main.js:18:5144
[native code]
handleTouchEnd@file:///var/containers/Bundle/Application/B7F05CCA-3B74-4F26-A691-B0D9F669E526/SGI.app/www/build/main.js:19:19943
[native code]

>

**Comment by matheuspf** [comment]
I don't know if this answers the question, but it worked for me:

~~~~
    firebase.auth().signOut().then(function() {
      // Sign-out successful.
      self.app.getRootNav().setRoot(LoginPage);
    }).catch(function(error) {
      // An error happened.
    });
~~~~

**Comment by nerdeveloper** [comment]
Hello @tonyawad88 
I tried to fix this by using 
`logout(){
  	this.navCtrl.setRoot("LoginPage");
     this.navCtrl.push("LoginPage");
   
  }`

This works like charm here

**Comment by nerdeveloper** [comment]
@tonyawad88 
This fixed the issue
```
logout(){
this.navCtrl.setRoot("LoginPage");
this.navCtrl.push("LoginPage");

}
```

**Comment by iamisti** [comment]
2 years old bug, still nobody dare to fix it... I'm having the same issue in Ionic 3

**Comment by mihirp1730** [comment]
Hello all,

I can get all my data from the root page also navigate but can't navigate the page out of tabs, its open like a child of tabs.

Tried all possibilities to solve it but no operation works.

Tab page where my data.
![1st](https://user-images.githubusercontent.com/24892060/36465806-ec667c38-16fc-11e8-9161-b2dd5e042d15.png)

After clicking on the fetched data it will redirect to the detail page of the data, it was redirect but inside the tab page. like this...

![2nd](https://user-images.githubusercontent.com/24892060/36465855-2f03eac6-16fd-11e8-969c-ed45adf0ceb7.png)

help me out,

Thanks in Advance.

**Comment by jknisley** [comment]
I have noticed this bug as of ionic-angular@3.9.2. It seems to be associated with the DeepLinkConfig, because if I remove that from my app.module then I can call nav.setRoot() all day long without issues. My hypothesis is that, after a subsequent call of of setRoot(), the deep link logic gets into a state where the nav stack changes before window.location, the deep link code sees that window.location points to a page that is not on the stack (because you've setRoot() away from it), and so it returns you to the page you just tried to nav away from.

Regardless, here is a workaround that works for me.
```
await this.nav.push(page, params)
this.nav.remove(0, this.nav.length() - 1)
```

**Comment by mihirp1730** [comment]
Thank you so much, 
I solved my issue with this.

```
detailEvent(eventItem) {
    this.app.getRootNav().push(DetailEventsPage, { itemUp: eventItem });  
  }
```
This code will redirect me to new page and diffrent layout(not under the tab page) too.

**Comment by alphapilgrim** [comment]
Just leaving this here for posterity. This logout function seems to be working for me without any side-effects. Thanks to @uiktiomasfeliz.


cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.2
    Cordova Platforms  : android 6.3.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2
    Node       : v8.9.1
    npm        : 5.7.1
    OS         : macOS High Sierra
    Xcode      : Xcode 9.3 Build version 9E145


```

async logOut() {
    await this.authProvider.logout();
    await this.app.getRootNav().setRoot('LoginPage');
  }

```

**Comment by Bandito11** [comment]
This is the way I found to set a new nav stack and removing the old nav stack. This was done for **ion-angular 3.9.2**
```
this.navCtrl.remove(0, this.navCtrl.length() - 1);
this.navCtrl.insert(0, MainPage);
this.navCtrl.pop();
```

**Comment by llinaresvicent** [comment]
In mi case, when I try to "come back" to root page with the method `setRoot()` and after that, inside the callback, call to `popToRoot()` it works but the page doesn't refresh. I know that worked because I can click on root page's buttons.
