### ISSUE TITLE
Ionic2 Navigation Tabs are not resizing correctly when deployed to iPhone6

### ISSUE THREAD

**Issue by bwalker72956** [driftyco/ionic#5886]
When deploying more than 3 tabs to an actual device (iPhone 6), the tabs are not resizing to fit the screen correctly.

Example App (Ionic2):
https://github.com/bwalker72956/testIonic2TabApp

Steps to reproduce:
1. I started with a sample app and added 2 additional tabs to navigation. 
2. I tested in the browser and emulator.  Everything worked fine.
3. When deployed to an actual device directly from xCode, the tabs run off the screen in Portrait mode.

**Comment by jgw96** [comment]
I can confirm this issue. Does not seem to happen in the iphone 6 simulator, but i can reproduce on my iphone 5.

**Comment by chinib** [comment]
Is this the same problem as #6056 ?

**Comment by bwalker72956** [comment]
This is the same issue.

**Comment by jgw96** [comment]
Hey all, this should be fixed in the latest nightly and will hit beta when beta.7 hits. To install Ionic 2 nightly you just run `npm install ionic-angular@nightly` in your project and you should be ready to go!

**Comment by bwalker72956** [comment]
Just tested it out and it works.  Thank you.

**Comment by jgw96** [comment]
@bwalker72956 Awesome! Nice to hear. Thanks for using Ionic!

**Comment by SanjanaTailor** [comment]
This is still the issue persist on 3.20.0 running the application on ipad devices where ios - max-width of tab = 240 px so that it cuts down from edges so what can be possible solution for it ? Android working fine
Thanks for any suggestions.
