### ISSUE TITLE
V2 - Beta 4 - White screen on real device with stater project

### ISSUE THREAD

**Issue by JumBay** [driftyco/ionic#6214]
#### Short description of the problem:
When I run the starter project on real devices (Nexus 5 & 5x android 6.0.1) I got a white screen. If I try on an emulator it works as expected.

When I have the white screen, if I press the hardware back button, and I reopen the app, without killing it it's working. 

#### What behavior are you expecting?
Having the app to work properly.

**Steps to reproduce:**
1. Create a new project: 
`ionic start cutePuppyPics --v2 --ts`
2. Build and deploy the project on the device
`ionic run android`
3. White screen.

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 
If I inspect the app with chrome, I don't see any errors, here is the console output:
```
whitelist.js:24 No Content-Security-Policy meta tag found. Please add one when using the cordova-plugin-whitelist plugin.

Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.

DEVICE READY FIRED AFTER 595 ms

No Content-Security-Policy meta tag found. Please add one when using the cordova-plugin-whitelist plugin.
```

**Which Ionic Version?**  2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
```
ionic info
WARN: ionic.config.js has been deprecated, you can remove it.

Your system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.4
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v5.10.1
Xcode version: Xcode 7.3 Build version 7D175
```

**Comment by davidhoeck** [comment]
I'm having the exact same problem. :-1:

**Comment by mpaland** [comment]
We had this discussion [here](https://forum.ionicframework.com/t/whitescreen-in-ionic2-templates/49137).
Seems to be fixed in beta.5

**Comment by adamdbradley** [comment]
Should be fixed in beta5, but could you try the nightly build and see if it fixes it? https://github.com/driftyco/ionic/tree/2.0/scripts#installing-nightly-version

**Comment by jgw96** [comment]
I can confirm that this was an issue with beta.4, but is fixed in nightly.

**Comment by JumBay** [comment]
I can confirm too it has been fixed in the nightly.

**Comment by ZiFFeL1992** [comment]
I'm having this issue only on iOS with latest nightly, no output errors, the same code is working on Android, seems like the app flow never reachs tabs.js

**Comment by jgw96** [comment]
@ZiFFeL1992 hey! Sorry your still having this issue! Would you be able to make a plunker that i can use to reproduce this issue? Are you only seeing it on ios? Or in the browser and on Android too?

**Comment by ZiFFeL1992** [comment]
@jgw96 both, android and iOS, check this: https://forum.ionicframework.com/t/promises-not-working-on-beta-5/49922/
