### ISSUE TITLE
<ion-navbar> inside Modal not working

### ISSUE THREAD

**Issue by Inoverse** [driftyco/ionic#6598]
Since the beta 7 the <ion-navbar> is no longer working inside a modal page. I have to changed it to <ion-toolbar> to make it running. Don't know if it is a bug or just a change.

Step to reproduce:
1. Add new page component (call it for example modal.ts):
```typescript
import {Page} from 'ionic-angular';

@Page({
  templateUrl: 'build/modal/modal.html',
})
export class ModalSample {
  constructor() {
  }
}
```
2. Add the related template file (modal.html):
```html
<ion-navbar *navbar primary>
    <ion-title>Title</ion-title>
</ion-navbar>

<ion-content>
    Test
</ion-content>
```
3. Open the modal, for example like:
```typescript
import {Page, NavController, Modal} from 'ionic-angular';
import {ModalSample} from './../../modal/modal';


@Page({
  templateUrl: 'build/pages/page1/page1.html',
})
export class Page1 {
  constructor(private nav: NavController) {
    this.openModal();
  }
  
  private openModal() {
    let modal = Modal.create(ModalSample);
    this.nav.present(modal);
  }
}
```

Result is, that the <ion.navbar> is not showing. Try editing the modal.html to <ion-toolbar> and it's working:
```html
<ion-toolbar primary>
    <ion-title>Title</ion-title>
</ion-toolbar>

<ion-content>
    Test
</ion-content>
```

Is this a new bug in the beta or a change?

**Comment by Luchillo** [comment]
Same issue here, modals doesn't work with `ion-navbar` anymore, however without it the back arrow and functionality is gone, this is a big issue, also none of the click events i put in the template works any more, that's a bigger issue.

**Comment by csysmans** [comment]
Another note (probably related):
The css class on the <ion-page> component inside the modal is missing (containing the name of the page).

**Comment by ciesielskico** [comment]
+1, `ion-navbar` in modals went missing with Beta 7.
```

<ion-navbar *navbar>
  <ion-title>{{title}}</ion-title>
  <ion-buttons end>
    <button (click)="dismissModal()">Cancel</button>
  </ion-buttons>
</ion-navbar>
```

The code above is not rendered anymore in a modal window, changing to `ion-toolbar` and adding own 'Cancel-button' instead of default back-button fixes the problem though.

**Comment by Luchillo** [comment]
That's great but i'm still experiencing UX blocking with modals due to the backdrop being on top of the modal itself, relate to this issue: https://github.com/driftyco/ionic/issues/6601

**Comment by ciesielskico** [comment]
Has to be something else,  maybe in your sass code,  modals work without a problem for me.

**Comment by Luchillo** [comment]
I'm not even touching the modals sass, however i will check all custom sass just in case.

**Comment by seedgabo** [comment]
fixed here. You need to change the ion-navbar *navbar for ion-toolbar, seems that ion-navbar only being rendering in a not modal page

before 

<ion-navbar primary  *navbar>
  <ion-title>Bug</ion-title>
  <ion-buttons end>
    <button (click)="close()">
      <ion-icon name="close" ></ion-icon>
    </button>
  </ion-buttons>
</ion-navbar >


<ion-toolbar primary >
  <ion-title>Fixed</ion-title>
  <ion-buttons end>
    <button (click)="close()">
      <ion-icon name="close" ></ion-icon>
    </button>
  </ion-buttons>
</ion-toolbar>

**Comment by Luchillo** [comment]
Hi @seedgabo what about the back button that `ion-navbar` generates by default?

**Comment by ciesielskico** [comment]
You add it by yourself using ion-buttons start/end as in the code above.

**Comment by danbucholtz** [comment]
Hi all, I'll take a look at this.  I pushed this code too early and for that I am sorry.

Thanks,
Dan

**Comment by jgw96** [comment]
Hey all! You can look on [this](https://github.com/driftyco/ionic/issues/6601) issue for a temporary workaround that i found for this issue.

**Comment by Luchillo** [comment]
@ciesielskico I added the toolbar and the back button by hand, now i can go back from modal, but the modal content is still blocked by the backdrop, yours work ok? i tested commenting all my css but it still has the backdrop blocking my user interactions.

**Comment by ciesielskico** [comment]
I have two different modal screens, both work fine. 
They are simple Ionic pages which are displayed like this:

```
let modal = Modal.create(TimepickerPage);
this.nav.present(modal);
```

Besides switching `ion-navbar` to `ion-toolbar` and changing some paddings I have not changed anything else. There must be something else in your code, HTML or scss. 
Maybe some changes in z-index?

**Comment by jgw96** [comment]
@ciesielskico are you on beta.7?

**Comment by Luchillo** [comment]
Just about to ask the same.

**Comment by ciesielskico** [comment]
Yep, as I have said in my first post. My package.json:  `"ionic-angular": "^2.0.0-beta.7"`.
Anyways, my problem was solved by changing navbar to toolbar. Good luck with the backdrop.

**Comment by danbucholtz** [comment]
Hi @Inoverse and others,

This should be fixed in nightly. Please let me know if you have any issues and I'll re-open. Thanks for contributing to Ionic!

Thanks,
Dan

**Comment by flavordaaave** [comment]
With beta-8 the <ion-navbar> is now visible again but the <ion-content> seems to have some extra padding on top of all pages inside the modal. Does someone else have the same issue?

**Comment by danbucholtz** [comment]
There are other inset modal updates that got chopped from beta 8 but are in beta 9, FYI.

Thanks,
Dan

**Comment by Luchillo** [comment]
@seedgabo This code presents errors when with Android styles:
```html
<ion-toolbar primary>
  <ion-buttons start>
    <button (click)="back()">
      <ion-icon name="arrow-back" ></ion-icon>
    </button>
  </ion-buttons>
  <ion-title>Notificaciones</ion-title>
</ion-toolbar>
```
Relate to issue: https://github.com/driftyco/ionic/issues/6842

**Comment by cherry-wave** [comment]
Hey guys, just wanted to ask what's the current state? I am new to Ionic2 and also have this prob:

```
        let modal = this.modalCtrl.create(PasswordResetPage, {email: this.credentials.email});
        modal.present();
```

passwordReset.html:

```
<ion-header>
    <ion-navbar>
        <ion-title>
            Password Reset
        </ion-title>
    </ion-navbar>
</ion-header>

<ion-content padding>
...
```

As said in this article I changed the ion-navbar tag to ion-toolbar but it still doesn't show the Cancel-Button. Do I really need to add it by hand?
