### ISSUE TITLE
StatusBar comes over Navbar when using Navbar as a common component - IOS only

### ISSUE THREAD

**Issue by shaikhspear16** [driftyco/ionic#6987]
I have a navbar in my application which consists a logout button throughout the application (except login screen) 
As this behavior remains constant I decided to create a common component for Nav Bar as follows
```

      <ion-navbar *navbar>
            <ion-title><img src={{titleImage}} /> {{pageTitle}}</ion-title>
            <ion-buttons end>
                <button (click)="logoutClick()"> Logout</button>
            </ion-buttons>
        </ion-navbar>
```

referring it into all the pages as 

`<navbar-selector [titleImage]="titleImage" [pageTitle]="pageTitle" ></navbar-selector>`

My component:

```

    @Component({
        selector: 'navbar-selector',
        template: `
        <ion-navbar *navbar>
            <ion-title><img src={{titleImage}} /> {{pageTitle}}</ion-title>
            <ion-buttons end>
                <button (click)="logoutClick()"> Logout</button>
            </ion-buttons>
        </ion-navbar>`
    })
    export class NavbarComponent {
        @Input()
        pageTitle: string;
        @Input()
        titleImage: string;

        error: boolean = false;
        errorResponse: any;

        constructor(private nav: NavController, private userAuthService: UserAuthService) {
            this.userAuthService = userAuthService;
            this.nav = nav;
        }

        logoutClick() {
          //logout logic
        }
    }

```

The problem here is that when ever I use this reusable component, the status bar comes over the NavBar  cluttering information from both. This happens only with IOS.

Once I remove the reusable component and utilize navbar in each page, navbar comes under status bar perfectly.

My work around to this problem:
added `margin-top:20px` for IOS only on `navbar-selector` element. I would like to know if there is a better way to handle.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us. This is happening because of something called content projection, which at a high level basically means the component is not being inserted into the dom where you think it should be. The good news is that this should be fixed by a layout refactor we are currently working on and should be in the next release. I will close this issue for now, but if It comes up when I test the new refactor I will happily reopen. In the meantime I would recommend just not using the custom component. Sorry for any hassle this causes, and thanks for using Ionic!

**Comment by cgs** [comment]
I'm also using a custom nav component and I'm still seeing this issue in 1.0.
