### ISSUE TITLE
Content padding is lost on first navigation.

### ISSUE THREAD

**Issue by zhl146** [driftyco/ionic#7642]
#### Short description of the problem:
I am currently using auth0 lock as a login screen. When I first navigate from the page that shows the lock using this.nav.setRoot(HomePage), I successfully navigate, but I do not have my padding applied on the ionic content. This results in my ionic-content hiding behind my toolbar.

I don't think this is a lock issue, as I believe it was happening to me when navigating through pure ionic pages. I think the issue stems from navigating from - to pages that have inconsistent headers.

#### What behavior are you expecting?
This what it looks like when I first navigate. If I inspect the dom element, there is no padding.
![image](https://cloud.githubusercontent.com/assets/17648674/17559943/1cc32764-5eee-11e6-970e-3e14f601205f.png)

This is what it looks like after I navigate away and then come back. If I inspect, the padding is correctly applied now.
![image](https://cloud.githubusercontent.com/assets/17648674/17559958/2bdf0e02-5eee-11e6-8c35-c4207adcbede.png)

**Steps to reproduce:**
1. Start with a page that has no header/toolbar/navbar.
2.  Navigate to a page that has a header/toolbar/navbar. (I think this results in the new ionic-content not having padding)
3.  Navigate away to a page that has content padding.
4.  Navigate back, I think it should fix the issue

 

**Which Ionic Version?** 
I am using ionic 2 beta 11 with angular2 RC4 and auth0 lock v10

Any help would be appreciated!

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you mind creating a repo with a minimal, ionic only, example that i can use to repro this issue? Thanks for using Ionic!

**Comment by zhl146** [comment]
I actually just tried to recreate the error in plunker, but was not able to :(

I had originally experienced this error before I added auth0, and I thought I identified the cause (above), but apparently it's not that reproducible.

I think I can probably come up with a workaround by forcing the user to go through a splash page with no header, but this is not ideal. Any insight would be appreciated!

**Comment by jgw96** [comment]
@zhl146 hmm unfortunately i have never used that particular library before so im not sure what could be causing the problem. I have tried to reproduce this issue in our tests and my test apps and unfortunately im not seeing this issue anywhere. I would recommend asking around on our [forum](forum.ionicframework.com) as im sure somebody else has used that particular library before. Since this does not seem to be strictly an ionic issue, but something to do with that library i will be closing this issue, but if you find that you can reproduce this issue with pure ionic then feel free to comment and i will happily reopen. Thanks for using Ionic!

**Comment by zhl146** [comment]
@jgw96 No problem. Thank you for getting back to me so quickly!

When I click on that forum link, I get a 404 error. Is it just me?

**Comment by jgw96** [comment]
No problem at all! Sorry bout that, the link is now fixed (:

**Comment by disko** [comment]
I do have the same error with a project, after upgrading from beta 8 to beta 11. Unfortunately I'm also unable to create a plunker :( At least I was able to debug a little. 

This is created for each tab:
```
ion-tab
  ion-page
    ion-header
    ion-content
      scroll-content
```

When viewing the tab for the first time ``scroll-content`` has no style attribute at all (for all tabs). On subsequent views ``style="margin-top: 56px; margin-bottom: 64px;"`` is applied and the issue vanishes.

**Comment by zhl146** [comment]
I found the same thing when i checked the styles.

Are you using any third party libraries to augment your view?

**Comment by zhl146** [comment]
@jgw96 I am still getting a 404 for the following:
https://github.com/driftyco/ionic/issues/forum.ionicframework.com

Is the issue on my end?

**Comment by disko** [comment]
@zhl146 no third party libraries w.r.t. views.

Link to the Forums is https://forum.ionicframework.com/ (works for me…)

**Comment by zhl146** [comment]
@disko Thanks! That link works.

Hope we can find what this issue is...

**Comment by SamuelTassell** [comment]
Hey guys, wondering if there is a work around for this? Getting the same issue. Cheers 😄

**Comment by wilkesreid** [comment]
Almost a year later and I'm having the same issue. I'm having a lot of trouble nailing down how to reproduce the issue though. It seems to occur almost randomly.

**Comment by wilkesreid** [comment]
Actually, I've been able to reproduce the issue in Ionic lab/serve this way:

1. reload Ionic lab
2. navigate to a different browser tab
3. wait for the Ionic lab tab to finish reloading
4. open the Ionic lab tab.

Doing this series of steps is reliably reproducing the issue for me.

**Comment by wilkesreid** [comment]
Okay, I think I've found the source of the bug, although I don't know why it's doing it or how to fix it yet.

The bug occurs for me when doing the steps I posted above and when, on load, a tab is being switched to by using a ViewChild (e.g. `@ViewChild('myTabs') tabRef: Tabs`) and calling `tabRef.select`.

**Comment by wilkesreid** [comment]
@jgw96 this appears to not be related to the auth0 library because I'm not using that library and I'm having the same issue.
