### ISSUE TITLE
Ionic 2, Beta 11, NavController push is now broken

### ISSUE THREAD

**Issue by tomgallagher** [driftyco/ionic#7751]
Hi

I've just updated to beta 11, hoping that it might fix the Popover problems I've been having on Android devices.

Sadly, the Beta 11 now seems to have broken my navigation. None of my this.nav.push(SettingsPage) commands now work.

Anyone else finding this or know what might be going wrong?

Cheers

Tom

**Comment by daviddk** [comment]
Tom, I'm not having issues with nav.push in my project, can you provide a code snippet? We might spot your fault.

**Comment by jgw96** [comment]
Hello @tomgallagher ! Thanks for opening an issue with us! Unfortunately i am also not able to reproduce any issues with the `push()` method of the `NavController`. Would you mind sharing a code snippet or repo that I can use to reproduce this issue? Thanks for using Ionic!

**Comment by tomgallagher** [comment]
Thanks for getting back.

I have an app whose navigation has been working for months.

I upgraded to beta 11 and all the Nav push commands have stopped working in the browser.

There's nothing very complicated going on.

` showSettings() {
    console.log("Clicked");
    this._navController.push(SettingsPage);
  }`

So either my move to beta 11 has not worked properly or something else is going on.

**Comment by jgw96** [comment]
Thanks for the info! Did you follow our [steps to update](https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#steps-to-upgrade-to-beta-11) to update your app?

**Comment by jgw96** [comment]
Awesome! Unfortunately i still cannot seem to reproduce. Are you able to reproduce this issue outside of your app? For example, if you start a new starter using `ionic start test-app --v2` could you try to reproduce it their?  Unfortunately I am not able to reproduce with any of our test apps.

**Comment by tomgallagher** [comment]
When I click to nav.push, the page gets pushed into the HTML, I can see it arrive in the browser console.  It has a z-index of 101 against 100 for the underlay page, but it also has an opacity of 0 in the CSS rules. When I change the opacity, the page is there, no back button though.

**Comment by jgw96** [comment]
@tomgallagher Ahh, it sounds like most likely you have some sort of error in your page that you are trying to push onto the stack that causes it to not get fully activated. Would you try reproducing this issue with a fresh project?

**Comment by tomgallagher** [comment]
Well I can try with a fresh page in my app, that would be a sensible thing to try. I'll report back.

**Comment by tomgallagher** [comment]
OK the fresh page works just fine so it's my problem. Thanks for the help.

**Comment by jgw96** [comment]
@tomgallagher Thanks for testing ! I would check and make sure that you renamed all of your methods correctly when you did the upgrade to beta.11. Most ide's such as vscode have really nice search functions that should be able to help. Thanks for using Ionic!

**Comment by tomgallagher** [comment]
Just one last thing, in your test apps, have you tried pushing pages to the NavController that include the new overlay syntax?

**Comment by tomgallagher** [comment]
And can I just check the following syntax with you?

`import {NavController, AlertController, PopoverController} from 'ionic-angular';`

`export class SettingsPage {
  static get parameters() {
    return [[NavController],[AlertController],[PopoverController],[DataStorage]];
  }`

  `constructor(_navController, _alertController, _popoverController, _dataStorage) {
    this._navController = _navController;
    this._alertController = _alertController;
    this._popoverController = _popoverController;`

Thanks for your time.

**Comment by jgw96** [comment]
@tomgallagher Yep! A few of my pages are using the new overlay component syntax. Quick question, are you using JavaScript or TypeScript?

**Comment by tomgallagher** [comment]
Javascript

**Comment by jgw96** [comment]
Ahh ok, unfortunately we do not support writing Ionic 2 apps in plain javascript anymore as of beta.9. Because of the immense advantages that Typescript gives you as an Ionic 2 developer we have decided to go all in on Typescript. You can read more about that decision [here](http://ionicframework.com/docs/v2/resources/typescript/). I would recommend going to our [forums](https://forum.ionicframework.com) as someone on their may still be using plain JavaScript. Thanks for using Ionic!

**Comment by tomgallagher** [comment]
So are you saying that there may not be any bugs in the code I have written, it may simply not work because it's written in Javascript? This is tough on me because Javascript was the Ionic 2 default when I started writing the app four months ago, I've got years of experience writing Javascript and it will leave me with a massive retooling to do.

**Comment by jgw96** [comment]
Hello @tomgallagher. Sorry, that is not what I am saying at all 😃 . It technically should still work fine, i am just not able to support it fully unfortunately because we do not officially support Ionic 2 apps written in JavaScript anymore. That is why i pointed you towards our forums. Thanks, and i hope that clears things up.

**Comment by tomgallagher** [comment]
The errors in my pages are caused by ngModel. Nothing I have changed in the last 2 months. Have you seen anything about that recently, in connection with beta11?

**Comment by tomgallagher** [comment]
This is the typical offending line in each page;

`<ion-input [(ngModel)]="home_URL" id="homeURL" type="text"></ion-input>`

**Comment by jgw96** [comment]
Ahh thanks for that info. So this issue was actually fixed this morning. The issue was that we had not specified a specific version of `@angular/forms` in our `npm install` command in our update guide. Because of this npm was installing a version of `@angular/forms` that was not compatible with the current version of Ionic 2. I fixed this with a commit this morning to the update guide. To fix it in your project you can just run `npm uninstall @angular/forms` and then run `npm install @angular/forms@0.2.0 --save-exact`.

**Comment by jgw96** [comment]
Just for reference here is my commit that fixed this https://github.com/driftyco/ionic/commit/82852fb353534210d6ecce7856c61d08e0449eb4

**Comment by tomgallagher** [comment]
Yes I think I was the person who pointed out that there must be a typo.

Sadly, this has not solved my problem. I am right in saying that ngModel is part of the core and does not need to be imported?  Or do I somehow need to import the angular forms module into each page where I'm using ngModel?  If so, do you know the syntax for this?

Thanks for answering all these questions. Sorry to be so useless, normally I'd just read a book but working with beta software....

Sometimes I wish I'd started with Ionic 1 but it just seemed pointless.

**Comment by jgw96** [comment]
No problem at all 😃 , just so you know though, you may get even more help on the [forums](https://forums.ionicframework.com). You are correct, ngModel is part of `@angular/core` and does not have to be explicitly imported. Are you using forms in your app at all currently?

**Comment by tomgallagher** [comment]
No just ngModel independently. I've also asked this same question on the forums, about beta 11 and ngModel. I guess I'll just have to wait and see what turns up.

**Comment by tomgallagher** [comment]
This guy has the same problem
https://forum.ionicframework.com/t/ive-just-updated-to-beta-11-and-the-below-stopped-working-ion-list-radio-group-ngmodel-content/60575

**Comment by jgw96** [comment]
What component are you using `ngModel` with?

**Comment by tomgallagher** [comment]
ion-input mostly

**Comment by tomgallagher** [comment]
Should I open a new issue with the ngModel observation?
