### ISSUE TITLE
Alert input without keyboard

### ISSUE THREAD

**Issue by pimol** [driftyco/ionic#9582]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

When an alert with input field presents the keyboard doesn't appears. You have to touch the input field to make the keyboard visible, despite focus is already on the input.

**Expected behavior:**

As soon as the alert comes up, the keyboard has to be shown

**Steps to reproduce:**

**Related code:**
```
let prompt = this.alertCtrl.create({
      title: 'Voce',
      inputs: [{
        name: "voce",
        placeholder: "scrivi qui",
      }],
      buttons: [{
        text: 'Annulla'
      }, {
        text: 'Salva',
        handler: data => {
          if (data.voce != "") { this.items.push(data.voce); }
          this.saveLs();
        }
      }]
    });
    prompt.present();

```
**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
 ordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v4.5.0
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Hello! Thanks for using Ionic! This issue was fixed in [RC.3](https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#200-rc3-2016-11-17) so you just need to update your app and that should fix it up for you 😃

**Comment by pimol** [comment]
Actually, I'm using RC3.
The app has been written before the RC3 release, but I rebuilt it. It's no enough? I have to change something in conf, too?

Thanks!

**Comment by pimol** [comment]
Sorry, my mistake. I didn't rebuilt.

P.

**Comment by pimol** [comment]
Actually, I check my configuration and now I'm using RC4: my ionic info

```
Your system information:

 ordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.47
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.2
Xcode version: Not installed
```
I still have the alert w/o the keybord that come up when I touch the input....
I hope you re-open the matter.

P.
